"use client";
import { useEffect, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Scanner } from "@yudiel/react-qr-scanner";
import { FaArrowRightFromBracket, FaCamera, FaCheck, FaClockRotateLeft, FaKeyboard, FaShieldHalved, FaStore, FaXmark } from "react-icons/fa6";
import TagsSpinner from "@/app/components/TagsSpinner";
import showAlert from "@/app/components/showAlert";
import "./BenefitMerchantValidator.css";
import "./BenefitMerchantValidatorHeader.css";

async function read(response){const text=await response.text();if(!text)return{ok:false,error:`Respuesta vacía (${response.status})`};try{return JSON.parse(text)}catch{return{ok:false,error:"La respuesta del servidor no es válida"}}}
function parseQr(value){try{const url=new URL(value);return{code:url.searchParams.get("code")||"",signature:url.searchParams.get("signature")||""}}catch{return{code:String(value||"").trim().toUpperCase(),signature:""}}}
const label=status=>status==="redeemed"?"Ya canjeado":status==="expired"?"Vencido":status==="cancelled"?"Cancelado":"Disponible para canjear";

export default function BenefitMerchantValidator(){
 const search=useSearchParams(),[session,setSession]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[email,setEmail]=useState(""),[code,setCode]=useState(search.get("code")||""),[signature,setSignature]=useState(search.get("signature")||""),[coupon,setCoupon]=useState(null),[scanner,setScanner]=useState(false);const scanned=useRef(false);
 async function loadSession(){const response=await fetch("/api/benefits/merchant/session",{cache:"no-store"}),payload=await read(response);setSession(response.ok?payload:null);setLoading(false);return response.ok}
 useEffect(()=>{loadSession()},[]);
 useEffect(()=>{if(session&&code)inspect(code,signature)},[session]);
 async function requestAccess(event){event.preventDefault();setBusy(true);try{const response=await fetch("/api/benefits/merchant/auth/request",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})}),payload=await read(response);await showAlert({title:response.ok?"Revisá tu email":"No se pudo enviar",text:response.ok?"Si el email corresponde a personal autorizado, recibirás el acceso al validador.":payload.error,icon:response.ok?"success":"error"})}finally{setBusy(false)}}
 async function inspect(nextCode=code,nextSignature=signature){const normalized=String(nextCode||"").trim().toUpperCase();if(!normalized)return showAlert({title:"Ingresá un código",icon:"warning"});setBusy(true);try{const params=new URLSearchParams({code:normalized});if(nextSignature)params.set("signature",nextSignature);const response=await fetch(`/api/benefits/merchant/validate?${params}`,{cache:"no-store"}),payload=await read(response);if(!response.ok)return showAlert({title:"Cupón no válido",text:payload.error,icon:"error"});setCode(normalized);setSignature(nextSignature||"");setCoupon(payload.coupon);setScanner(false)}finally{setBusy(false)}}
 async function redeem(){const ok=await showAlert({title:"¿Confirmar el canje?",text:`${coupon.benefitName} · Cupón ${coupon.code}. Esta acción lo marcará como utilizado.`,icon:"question",showCancelButton:true,confirmButtonText:"Confirmar canje",cancelButtonText:"Cancelar"});if(!ok)return;setBusy(true);try{const response=await fetch("/api/benefits/merchant/validate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:coupon.code,signature})}),payload=await read(response);if(!response.ok)return showAlert({title:"No se pudo canjear",text:payload.error,icon:"error"});setCoupon(payload.coupon);await showAlert({title:"Cupón canjeado",text:"El uso quedó registrado correctamente.",icon:"success"});await loadSession()}finally{setBusy(false)}}
 async function logout(){await fetch("/api/benefits/merchant/session",{method:"DELETE"});setSession(null);setCoupon(null)}
 function onScan(result){if(scanned.current||!result?.[0]?.rawValue)return;scanned.current=true;const parsed=parseQr(result[0].rawValue);inspect(parsed.code,parsed.signature).finally(()=>setTimeout(()=>{scanned.current=false},1200))}
 if(loading)return <TagsSpinner size={110} logoSize={58}/>;
 if(!session)return <main className="tags_benefit_validator_login"><section><FaShieldHalved/><span>VALIDADOR TAGS</span><h1>Canje de beneficios</h1><p>Ingresá con el email autorizado por el comercio.</p><form onSubmit={requestAccess}><label>Email<input required type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="personal@comercio.com"/></label><button disabled={busy}>Recibir enlace de acceso</button></form><small>No brinda acceso a reservas ni a información privada del alojamiento.</small></section>{busy&&<TagsSpinner size={100} logoSize={52} background="rgba(255,255,255,.75)"/>}</main>;
 return <main className="tags_benefit_validator"><header><div><FaStore/><div><span>VALIDADOR TAGS</span><h1>{session.merchant.name}</h1><p>{session.staff.name}</p></div></div><button onClick={logout}><FaArrowRightFromBracket/> Salir</button></header><section className="tags_benefit_validator_controls"><button onClick={()=>setScanner(true)}><FaCamera/> Escanear QR</button><form onSubmit={event=>{event.preventDefault();inspect()}}><label><FaKeyboard/><input value={code} onChange={event=>setCode(event.target.value)} placeholder="TAG-XXXXXXXXXX"/></label><button disabled={busy}>Buscar cupón</button></form></section>{coupon&&<section className="tags_benefit_validator_coupon"><span className={`is_${coupon.status}`}>{label(coupon.status)}</span><h2>{coupon.benefitName}</h2><strong>{coupon.code}</strong><dl><div><dt>Huésped</dt><dd>{coupon.guestName||"Usuario Tags"}</dd></div>{coupon.stayCode&&<div><dt>Estadía</dt><dd>{coupon.stayCode}</dd></div>}<div><dt>Vencimiento</dt><dd>{new Date(coupon.expiresAt).toLocaleString("es-AR")}</dd></div></dl>{coupon.conditions&&<p>{coupon.conditions}</p>}{coupon.status==="issued"?<button onClick={redeem} disabled={busy}><FaCheck/> Confirmar canje</button>:<div className="tags_benefit_validator_result"><FaClockRotateLeft/> {coupon.status==="redeemed"&&coupon.redeemedAt?`Canjeado el ${new Date(coupon.redeemedAt).toLocaleString("es-AR")}`:label(coupon.status)}</div>}</section>}<section className="tags_benefit_validator_recent"><h2>Últimos canjes</h2>{session.recent.map(item=><article key={item.id}><div><strong>{item.benefit_name}</strong><span>{item.code}</span></div><small>{new Date(item.redeemed_at).toLocaleString("es-AR")}</small></article>)}{!session.recent.length&&<p>Todavía no hay canjes registrados.</p>}</section>{scanner&&<div className="tags_benefit_scanner_backdrop"><section><header><h2>Escanear cupón</h2><button onClick={()=>setScanner(false)}><FaXmark/></button></header><div className="tags_benefit_scanner_camera"><Scanner constraints={{facingMode:"environment"}} onScan={onScan} onError={()=>{}}/></div><p>Enfocá el QR que aparece en el teléfono del huésped.</p></section></div>}{busy&&<TagsSpinner size={105} logoSize={55} background="rgba(255,255,255,.72)"/>}</main>
}
