export const runtime="nodejs";
export const dynamic="force-dynamic";
import {db} from "@/app/lib/tags-db";
import {getSessionUser} from "@/app/modules/users/lib/userSession";
import {createCouponCode,requestIp,signCouponCode} from "@/app/modules/benefits/lib/benefitService";
import {getRequestBaseUrl} from "@/app/lib/channelContext";

function couponView(item,origin){if(!item)return null;const signature=signCouponCode(item.code);return{id:item.id,code:item.code,status:item.status,issuedAt:item.issued_at,expiresAt:item.expires_at,redeemedAt:item.redeemed_at,qrPayload:`${origin}/beneficios/validar?code=${encodeURIComponent(item.code)}&signature=${signature}`}}

async function benefit(id,connection=db){const[rows]=await connection.query(`SELECT d.*,COALESCE(NULLIF(b.display_name,''),b.name) business_name,b.email business_email,b.phone business_phone FROM tags_directory_benefits d INNER JOIN tags_businesses b ON b.id=d.business_id WHERE d.id=? AND d.visibility='public' AND d.is_active=1 AND d.valid_from<=CURDATE() AND d.valid_until>=CURDATE() LIMIT 1`,[id]);return rows[0]||null}

export async function GET(request){const session=await getSessionUser();if(!session)return Response.json({success:false,error:"No autenticado"},{status:401});const benefitId=Number(new URL(request.url).searchParams.get("benefit_id")||0),item=await benefit(benefitId);if(!item)return Response.json({success:false,error:"Beneficio no encontrado"},{status:404});const origin=getRequestBaseUrl(request)||new URL(request.url).origin;const[coupons]=await db.query(`SELECT c.* FROM tags_benefit_coupons c INNER JOIN tags_benefit_campaigns ca ON ca.id=c.campaign_id WHERE ca.source_directory_benefit_id=? AND c.user_id=? ORDER BY c.issued_at DESC LIMIT 1`,[benefitId,session.userId]);return Response.json({success:true,benefit:item,coupon:couponView(coupons[0],origin)})}

export async function POST(request){const session=await getSessionUser();if(!session)return Response.json({success:false,error:"No autenticado"},{status:401});const body=await request.json().catch(()=>null),benefitId=Number(body?.benefit_id||0),connection=await db.getConnection();try{await connection.beginTransaction();const item=await benefit(benefitId,connection);if(!item)throw new Error("El beneficio no está disponible");if(item.validation_mode==="display"){await connection.rollback();return Response.json({success:true,benefit:item,coupon:null,displayOnly:true})}
 const[merchantResult]=await connection.query(`INSERT INTO tags_benefit_merchants (business_id,created_by_business_id,name,email,phone,status) VALUES (?,?,?,?,?,'active') ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),name=VALUES(name),email=VALUES(email),phone=VALUES(phone),status='active',updated_at=NOW()`,[item.business_id,item.business_id,item.business_name,item.business_email,item.business_phone]);const merchantId=merchantResult.insertId;
 let[campaignRows]=await connection.query(`SELECT * FROM tags_benefit_campaigns WHERE source_directory_benefit_id=? AND guest_app_id IS NULL LIMIT 1`,[item.id]);let campaign=campaignRows[0];if(!campaign){const[result]=await connection.query(`INSERT INTO tags_benefit_campaigns (merchant_id,issuer_type,issuer_business_id,source_directory_benefit_id,name,image_url,description,conditions_text,benefit_type,benefit_value,valid_from,valid_until,limit_scope,max_issues,scope_type,status) VALUES (?,'directory',?,?,?,?,?,?,?,?,?,?,'user',1,'directory','published')`,[merchantId,item.business_id,item.id,item.name,item.image_url,item.description,item.description,item.benefit_type,item.benefit_value,item.valid_from,item.valid_until]);campaign={id:result.insertId}}
 const[existing]=await connection.query(`SELECT * FROM tags_benefit_coupons WHERE campaign_id=? AND user_id=? AND status IN ('issued','redeemed') ORDER BY issued_at DESC LIMIT 1`,[campaign.id,session.userId]);let coupon=existing[0];if(!coupon){const code=createCouponCode(),signature=signCouponCode(code),expiresAt=new Date(`${String(item.valid_until).slice(0,10)}T23:59:59`);const[result]=await connection.query(`INSERT INTO tags_benefit_coupons (campaign_id,code,signature_hash,user_id,status,expires_at) VALUES (?,?,?,?,'issued',?)`,[campaign.id,code,signature,session.userId,expiresAt]);const[created]=await connection.query(`SELECT * FROM tags_benefit_coupons WHERE id=?`,[result.insertId]);coupon=created[0]}
 await connection.commit();const origin=getRequestBaseUrl(request)||new URL(request.url).origin;return Response.json({success:true,benefit:item,coupon:couponView(coupon,origin)});
 }catch(error){await connection.rollback();console.error("USER DIRECTORY BENEFIT ISSUE ERROR",error);return Response.json({success:false,error:error.message||"No se pudo emitir el cupón"},{status:400})}finally{connection.release()}}

export async function PATCH(request){const session=await getSessionUser();if(!session)return Response.json({success:false,error:"No autenticado"},{status:401});const body=await request.json().catch(()=>null),couponId=Number(body?.coupon_id||0),connection=await db.getConnection();try{await connection.beginTransaction();const[rows]=await connection.query(`SELECT c.*,ca.merchant_id,d.validation_mode FROM tags_benefit_coupons c INNER JOIN tags_benefit_campaigns ca ON ca.id=c.campaign_id INNER JOIN tags_directory_benefits d ON d.id=ca.source_directory_benefit_id WHERE c.id=? AND c.user_id=? FOR UPDATE`,[couponId,session.userId]);const item=rows[0];if(!item)throw new Error("Cupón no encontrado");if(item.validation_mode!=="visual")throw new Error("Este beneficio debe validarlo el comercio");if(item.status!=="issued")throw new Error(item.status==="redeemed"?"El cupón ya fue utilizado":"El cupón no está disponible");if(item.expires_at&&new Date(item.expires_at)<new Date())throw new Error("El cupón está vencido");const[result]=await connection.query(`INSERT INTO tags_benefit_redemptions (coupon_id,merchant_id,status,ip_address,user_agent,notes) VALUES (?,?,'confirmed',?,?,?)`,[item.id,item.merchant_id,requestIp(request),String(request.headers.get("user-agent")||"").slice(0,500),"Validación visual iniciada por el usuario"]);await connection.query(`UPDATE tags_benefit_coupons SET status='redeemed',redeemed_at=NOW() WHERE id=?`,[item.id]);await connection.query(`INSERT INTO tags_benefit_audit_log (merchant_id,campaign_id,coupon_id,actor_type,actor_id,action,metadata_json,ip_address) VALUES (?,?,?,'user',?,'coupon.visual_redeemed',?,?)`,[item.merchant_id,item.campaign_id,item.id,session.userId,JSON.stringify({redemptionId:result.insertId}),requestIp(request)]);await connection.commit();const origin=getRequestBaseUrl(request)||new URL(request.url).origin;return Response.json({success:true,coupon:couponView({...item,status:"redeemed",redeemed_at:new Date()},origin)})}catch(error){await connection.rollback();return Response.json({success:false,error:error.message||"No se pudo utilizar el cupón"},{status:400})}finally{connection.release()}}
