"use client";

import { useState } from "react";
import Link from "next/link";
import {
  FaArrowLeft, FaArrowRight, FaBriefcase, FaBus, FaCalendarCheck, FaCampground,
  FaCartShopping, FaGift, FaGlobe, FaHotel, FaHouse, FaIdCard, FaMagnifyingGlass,
  FaMapLocationDot, FaQrcode, FaRobot, FaStar, FaStore, FaSuitcaseRolling,
  FaTags, FaUmbrellaBeach, FaUtensils, FaWhatsapp, FaXmark
} from "react-icons/fa6";

const productDetails = {
  id: { eyebrow:"TARJETA PERSONAL DIGITAL CORPORATIVA", intro:"Presentate de manera inteligente y elegante con una tarjeta digital que reúne tu identidad profesional y tus datos importantes.", desktop:"/assets/images/calamuchitar/productos/tags_id_desk.webp", mobile:"/assets/images/calamuchitar/productos/tags_id_mobile.webp", features:["Nombre, profesión, especialidad y presentación","Teléfono, WhatsApp, email y redes sociales","Enlaces a tu Página Web, portfolio o servicios","Compartila mediante QR o NFC desde un soporte físico"], advantages:["Una presentación profesional","Tus datos siempre actualizados","Contacto en pocos pasos","Ideal para profesionales y equipos"] },
  stay: { eyebrow:"MI ESTADÍA PARA ALOJAMIENTOS", intro:"Administrá tus reservas y acompañá a tus huéspedes desde la confirmación hasta el final de su estadía.", desktop:"/assets/images/calamuchitar/productos/miestadia_desk.webp", mobile:"/assets/images/calamuchitar/productos/miestadia_mobile.webp", features:["Reservas, disponibilidad y datos de los huéspedes","Pagos, cuenta de la estadía y adicionales","Pre-checkin, checkin y checkout","Información útil, WiFi, reglamento, beneficios y servicios adicionales"], advantages:["Menos tareas manuales","Huéspedes mejor informados","Una experiencia diferencial","Todo administrado desde tu panel"] },
  qr: { eyebrow:"QR Y NFC PARA TU NEGOCIO", intro:"Compartí información y acciones actualizables con un código que podés seguir usando aunque cambies el contenido.", desktop:"/assets/images/calamuchitar/productos/qrs_dinamicos_desk.webp", mobile:"/assets/images/calamuchitar/productos/qrs_dinamicos_mobile.webp", features:["Enlaces actualizables","QR para páginas, redes, WhatsApp y reseñas","Estadísticas de escaneos","Pausa, reactivación y mensaje personalizado"], advantages:["No tenés que reimprimir el código","Acceso rápido desde cualquier celular","Ideal para cartelería, vidrieras y productos"] },
  web: { eyebrow:"PÁGINA WEB PERSONALIZADA", intro:"Presentá tu negocio con una página clara, profesional y autoadministrable, pensada para que te encuentren y te contacten.", desktop:"/assets/images/calamuchitar/productos/paginaweb_desk.webp", mobile:"/assets/images/calamuchitar/productos/paginaweb_mobile.webp", features:["Información, servicios y productos","Logo, galería, redes y datos de contacto","Mapa, ubicación y cómo llegar","Secciones editables y optimizadas para buscadores"], advantages:["Tu presencia propia en internet","Contenido siempre actualizado","Una página que puede crecer con tu negocio"] },
  store: { eyebrow:"CATÁLOGO O TIENDA ONLINE", intro:"Desde una presentación simple de productos o servicios hasta una tienda profesional para vender por internet.", desktop:"/assets/images/calamuchitar/productos/tienda_desk.webp", mobile:"/assets/images/calamuchitar/productos/tienda_moobile.webp", features:["Categorías, imágenes, descripciones y precios","Catálogo QR/NFC para consultas rápidas","Carrito de compras y pedidos","Pagos online, envíos y seguimiento según la herramienta contratada"], advantages:["Vendé todos los días","Ordená tu oferta","Empezá simple y sumá funciones cuando las necesites"] },
  resto: { eyebrow:"CARTA Y PEDIDOS RESTO", intro:"Convertí tu carta en una experiencia digital y recibí pedidos desde la mesa, Take Away y Delivery.", desktop:"/assets/images/calamuchitar/productos/resto_desk.webp", mobile:"/assets/images/calamuchitar/productos/resto_mobile.webp", features:["Carta digital con categorías y productos","Pedido desde la mesa mediante QR","Take Away y Delivery","Estados del pedido, cocina, caja y comunicación"], advantages:["Menos errores al tomar pedidos","Atención más rápida","Desde una carta simple hasta una operación completa"] },
  turns: { eyebrow:"TURNOS Y RESERVAS", intro:"Organizá tu agenda y permití que tus clientes reserven horarios de forma simple.", desktop:"/assets/images/calamuchitar/productos/turnos_desk.webp", mobile:"/assets/images/calamuchitar/productos/turnos_mobile.webp", features:["Horarios y disponibilidad","Profesionales, canchas, salas o equipos","Reservas, cancelaciones y reprogramaciones","Recordatorios y administración desde tu panel"], advantages:["Menos cruces de horarios","Agenda ordenada","Adaptable a distintos servicios y actividades"] },
  reviews: { eyebrow:"TAGS REVIEWS · RESEÑAS DE CLIENTES", intro:"Recibí opiniones, administralas y elegí cuáles mostrar para generar confianza.", desktop:"/assets/images/calamuchitar/productos/resenias_desk.webp", mobile:"/assets/images/calamuchitar/productos/resenias_mobile.webp", features:["Formulario configurable","Reseñas privadas y públicas","Moderación desde el panel","Bloque de reseñas en tu Página Web"], advantages:["Más confianza para comprar o reservar","Opiniones visibles y ordenadas","Destacá las experiencias que representan tu negocio"] },
  loyalty: { eyebrow:"BENEFICIOS Y FIDELIZACIÓN", intro:"Creá propuestas para que tus clientes vuelvan: descuentos, puntos, sellos, visitas y recompensas.", desktop:"/assets/images/calamuchitar/productos/beneficios_desk.webp", mobile:"/assets/images/calamuchitar/productos/beneficios_mobile.webp", features:["Programas de puntos, sellos o visitas","Recompensas configurables","Beneficios privados o públicos","Seguimiento y validación"], advantages:["Premiá la frecuencia","Construí una relación con tus clientes","Convertí una visita en una nueva oportunidad"] },
  chatbot: { eyebrow:"CHATBOT EN TU WEB", intro:"Un asistente disponible las 24 horas, entrenado con la información real de tu negocio.", desktop:"/assets/images/calamuchitar/productos/chatbot_desk.webp", mobile:"/assets/images/calamuchitar/productos/chatbot_mobile.webp", features:["Base de conocimiento propia","Respuestas sobre servicios, horarios y productos","Widget configurable","Integración en tu Página Web"], advantages:["Respondé aunque estés ocupado","Evitá repetir información","Atención inicial más rápida"] }
};

const options = [
  { id:"business", kind:"client", icon:FaStore, visualIcons:[FaStore,FaBriefcase,FaCartShopping], title:"¿Tenés un Comercio u Ofrecés un Producto o Servicio?", summary:"Hacé visible tu negocio y conectá con nuevos clientes.", text:"CalamuchitAr te ayuda a mostrar tu actividad, tus productos y tus medios de contacto.", action:["Ingresar a la Plataforma","/directorio"], details:[
    ["qr",FaQrcode,"QRs Dinámicos para tu Negocio","Compartí información, enlaces y acciones actualizables mediante códigos QR."], ["web",FaGlobe,"Página Web Personalizada y Autoadministrable","Presentá tu negocio en una página propia, clara y fácil de mantener."], ["store",FaStore,"Catálogo o Tienda de Productos o Servicios","Mostrá tus productos o servicios, desde un catálogo simple hasta una tienda online."], ["resto",FaUtensils,"Carta de Menú y Pedidos Resto","Ofrecé tu carta digital y recibí pedidos desde la Mesa, Take Away y Delivery."], ["turns",FaCalendarCheck,"Turnos y Reservas","Organizá turnos y reservas para que tus clientes puedan elegir horarios."], ["reviews",FaStar,"Reseñas de Clientes","Recibí opiniones, administralas y elegí cuáles mostrar en tu página web."], ["loyalty",FaTags,"Beneficios y Programas de Fidelización de Clientes","Ofrecé descuentos, puntos, sellos y recompensas."], ["chatbot",FaRobot,"ChatBot en tu Web","Un asistente entrenado con tu información para responder por vos las 24 horas."]
  ]},
  { id:"lodging", kind:"client", icon:FaHotel, visualIcons:[FaHotel,FaHouse,FaCampground], title:"¿Tenés un Alojamiento Temporario?", summary:"Cabañas, hoteles, posadas, hosterías y camping.", text:"Mejorá la experiencia de tus huéspedes desde el momento de la reserva.", action:["Conocer Mi Estadía","/publicar-mi-negocio?perfil=alojamiento"], details:[["stay",FaHotel,"Mi Estadía","Administrá reservas y pagos y ofrecé una experiencia completa."],["reviews",FaStar,"Reseñas de Clientes","Recibí opiniones de tus huéspedes."],["loyalty",FaTags,"Beneficios y Fidelización","Ofrecé descuentos y recompensas."],["chatbot",FaRobot,"ChatBot en tu Web","Respondé consultas durante las 24 horas."]]},
  { id:"professional", kind:"client", icon:FaIdCard, visualIcons:[FaIdCard,FaBriefcase,FaGlobe], title:"¿Sos Profesional?", summary:"Presentate de manera inteligente y elegante.", text:"Mostrá quién sos, qué hacés y cómo contactarte.", action:["Conocer Tags ID","/tags-id"], details:[["id",FaIdCard,"Tarjeta Personal Digital Corporativa","Reuní tu presentación, contacto, redes y enlaces importantes."]]},
  { id:"tourism", kind:"user", icon:FaSuitcaseRolling, visualIcons:[FaSuitcaseRolling,FaBus,FaUmbrellaBeach], title:"¿Estás Haciendo Turismo en el Valle de Calamuchita?", summary:"Planificá tu visita y descubrí lugares, actividades y propuestas.", text:"Encontrá lo que necesitás durante tu viaje.", action:["Conocer Calamuchita","/directorio"], details:[["sleep",FaHouse,"Dónde Dormir","Alojamientos por localidad."],["eat",FaUtensils,"Dónde Comer","Restaurantes y propuestas gastronómicas."],["do",FaUmbrellaBeach,"Qué Hacer","Actividades y experiencias."],["gift",FaGift,"Dónde Comprar","Regalos y productos regionales."]]},
  { id:"search", kind:"user", icon:FaMagnifyingGlass, visualIcons:[FaMagnifyingGlass,FaStore,FaBriefcase], title:"¿Estás Buscando un Producto o Servicio?", summary:"Encontrá comercios, profesionales y prestadores cerca tuyo.", text:"Buscá por nombre, rubro o localidad.", action:["Buscar en CalamuchitAr","/directorio"], details:[["shops",FaStore,"Comercios","Encontrá productos y negocios de la zona."],["services",FaBriefcase,"Servicios","Contactá profesionales y prestadores."],["places",FaMapLocationDot,"Por Localidad","Elegí la localidad más cercana."]]}
];

export default function CalamuchitarExperience(){
  const [selected,setSelected]=useState(null),[detail,setDetail]=useState(null);
  const option=options.find(item=>item.id===selected), MainIcon=option?.icon;
  const openOption=item=>item.id==="professional"?setDetail(item.details[0]):setSelected(item.id);
  const product=detail?(productDetails[detail[0]]||{eyebrow:"CALAMUCHITAR",intro:detail[3],desktop:"/assets/images/calamuchitar/buscando_900x1200.webp",mobile:"/assets/images/calamuchitar/buscando_900x1200.webp",features:[detail[3]],advantages:["Información local reunida","Acceso simple y directo"]}):null;
  return <div className="tags_experience_shell">
    <section className="tags_experience_hero"><div className="tags_experience_hero_overlay"/><div className="tags_experience_hero_content"><span>CALAMUCHITAR</span><h1>Todo Calamuchita<br/>en un solo lugar</h1><p>Descubrí nuevas oportunidades, encontrá lo que necesitás y conocé cómo hacer crecer tu negocio en el Valle.</p><div className="tags_experience_hero_badge"><FaMapLocationDot/> La Plataforma Comercial de Calamuchita</div></div></section>
    {option?<section className="tags_experience_detail" aria-live="polite"><button className="tags_experience_back" type="button" onClick={()=>{setSelected(null);setDetail(null)}}><FaArrowLeft/> Volver</button><div className="tags_experience_detail_heading"><span className="tags_experience_detail_icon"><MainIcon/></span><div><span>CALAMUCHITAR TE ACOMPAÑA</span><h2>{option.title}</h2><p>{option.text}</p></div></div><div className="tags_experience_detail_grid">{option.details.map(item=>{const Icon=item[1];return <article className="tags_experience_detail_card" key={item[2]}><button type="button" onClick={()=>setDetail(item)}><span><Icon/><strong>{item[2]}</strong></span><FaArrowRight/></button><p>{item[3]}</p></article>})}</div><div className="tags_experience_cta"><div><span>DESCUBRÍ TODO LO QUE PODÉS HACER</span><h3>Ingresá y Conocé CalamuchitAr</h3><p>La Plataforma Comercial de Calamuchita</p></div><div className="tags_experience_cta_actions"><Link href={option.action[1]}>{option.action[0]} <FaArrowRight/></Link></div></div></section>:<><section className="tags_experience_profiles"><header><span>CALAMUCHITAR</span><h2>Conocé Todo lo que Tenemos para Vos</h2><p>Elegí una opción y descubrí las oportunidades, servicios y herramientas disponibles.</p></header><div className="tags_experience_profile_grid">{options.map(item=><button type="button" className={`tags_experience_profile_card ${item.kind==="client"?"is_client":"is_user"}`} onClick={()=>openOption(item)} key={item.id}><span className="tags_experience_profile_visuals">{item.visualIcons.map((Icon,index)=><i key={index}><Icon/></i>)}</span><span className="tags_experience_profile_title">{item.title}</span><span className="tags_experience_profile_summary">{item.summary}</span><span className="tags_experience_profile_action">Conocer Más <FaArrowRight/></span></button>)}</div></section><section className="tags_experience_final"><FaGift/><h2>Una Plataforma para Descubrir y Crecer en Calamuchita</h2><p>Elegí una opción para conocer la propuesta que tenemos para vos.</p></section></>}
    <div className="tags_experience_contact"><strong>¿Querés Hablar con Nosotros?</strong><a href="https://wa.me/543546562855" target="_blank" rel="noreferrer"><FaWhatsapp/> Escribinos por WhatsApp</a></div>
    <section className="tags_experience_seo" aria-labelledby="calamuchitar-seo-title"><h2 id="calamuchitar-seo-title">¿Qué es CalamuchitAr?</h2><p>CalamuchitAr es la Plataforma Comercial de Calamuchita: un espacio que conecta a quienes buscan productos y servicios con comercios, profesionales y prestadores de toda la región.</p><p>Desarrollamos herramientas digitales para cada tipo de negocio e implementamos soluciones a medida, simples y seguras. Ponemos a disposición buscadores con filtros, mapas, indicaciones para llegar y medios de contacto.</p><p>Además, impulsamos un sistema de beneficios para ofrecer descuentos, puntos y recompensas, fomentando la actividad comercial regional mediante tecnología accesible.</p></section>
    {detail&&product&&<div className="tags_experience_product_modal_backdrop" role="presentation" onClick={()=>setDetail(null)}><div className="tags_experience_product_modal" role="dialog" aria-modal="true" aria-labelledby="experience-product-modal-title" onClick={event=>event.stopPropagation()}><button className="tags_experience_product_modal_close" type="button" aria-label="Cerrar" onClick={()=>setDetail(null)}><FaXmark/></button><div className="tags_experience_product_modal_header"><span className="tags_experience_product_modal_icon">{(()=>{const Icon=detail[1];return <Icon/>})()}</span><div><span>{product.eyebrow}</span><h2 id="experience-product-modal-title">{detail[2]}</h2><p>{product.intro}</p></div></div><div className="tags_experience_product_modal_media"><picture><source media="(max-width: 620px)" srcSet={product.mobile}/><img src={product.desktop} alt={detail[2]}/></picture></div><div className="tags_experience_product_modal_columns"><section><h3>¿Qué podés hacer?</h3>{product.features.map(item=><div className="tags_experience_product_modal_feature" key={item}><FaArrowRight/><span>{item}</span></div>)}</section><section className="tags_experience_product_modal_advantages"><h3>¿Por qué te sirve?</h3>{product.advantages.map(item=><div className="tags_experience_product_modal_feature" key={item}><FaGift/><span>{item}</span></div>)}</section></div><div className="tags_experience_product_modal_footer"><strong>¿Querés conocer más sobre esta herramienta?</strong><a className="tags_experience_product_modal_whatsapp" href={`https://wa.me/543546562855?text=${encodeURIComponent(`Estoy interesado en saber más acerca de ${detail[2]}`)}`} target="_blank" rel="noreferrer"><FaWhatsapp/> Consultanos!</a></div></div></div>}
  </div>;
}
