export const DIRECTORY_PRODUCT_LINKS = [
  ["qr-dinamicos", "QRs Dinámicos para tu Negocio"],
  ["pagina-web", "Página Web Personalizada"],
  ["catalogo-tienda", "Catálogo o Tienda Online"],
  ["resto", "Carta y Pedidos Resto"],
  ["turnos-reservas", "Turnos y Reservas"],
  ["resenias", "Reseñas de Clientes"],
  ["beneficios-fidelizacion", "Beneficios y Fidelización"],
  ["chatbot", "ChatBot en tu Web"],
  ["tags-id", "Tags ID (Tarjeta Personal Digital Inteligente)"],
  ["mi-estadia", "Mi Estadía para Alojamientos"],
];

export const DIRECTORY_PRODUCT_PAGES = {
  "qr-dinamicos": {
    title: "QRs Dinámicos para tu Negocio",
    eyebrow: "QR Y NFC PARA NEGOCIOS",
    description: "Convertí un código QR o un soporte NFC en una puerta de entrada a tu negocio, tus productos, tus redes y tus canales de contacto.",
    imageDesk: "/assets/images/calamuchitar/productos/qrs_dinamicos_desk.webp",
    imageMobile: "/assets/images/calamuchitar/productos/qrs_dinamicos_mobile.webp",
    alt: "Soportes QR y NFC para comercios y prestadores",
    features: ["Enlaces y destinos actualizables", "QR para páginas, WhatsApp, redes, menús y reseñas", "Estadísticas de escaneos", "Pausa, reactivación y mensaje personalizado"],
    benefits: ["No necesitás reimprimir el código cuando cambia la información", "Funciona en carteles, vidrieras, productos, mesas y tarjetas", "Podés comenzar con una acción simple y sumar nuevas experiencias"],
  },
  "pagina-web": {
    title: "Página Web Personalizada y Autoadministrable",
    eyebrow: "TU PRESENCIA DIGITAL",
    description: "Presentá tu negocio con una Página Web clara, profesional y fácil de mantener, preparada para que te encuentren y te contacten.",
    imageDesk: "/assets/images/calamuchitar/productos/paginaweb_desk.webp",
    imageMobile: "/assets/images/calamuchitar/productos/paginaweb_mobile.webp",
    alt: "Ejemplo de Página Web personalizada",
    features: ["Información, servicios y productos", "Logo, galería, redes y datos de contacto", "Mapa, ubicación y cómo llegar", "Secciones editables y contenido preparado para buscadores"],
    benefits: ["Tu negocio tiene una presencia propia en internet", "La información queda centralizada y siempre actualizada", "Podés sumar otras herramientas según tus necesidades"],
  },
  "catalogo-tienda": {
    title: "Catálogo o Tienda de Productos y Servicios",
    eyebrow: "MOSTRÁ Y VENDÉ",
    description: "Desde un catálogo simple para mostrar tu oferta hasta una tienda online profesional para recibir y administrar pedidos.",
    imageDesk: "/assets/images/calamuchitar/productos/tienda_desk.webp",
    imageMobile: "/assets/images/calamuchitar/productos/tienda_moobile.webp",
    alt: "Ejemplo de catálogo y tienda online",
    features: ["Categorías, imágenes, descripciones y precios", "Catálogo accesible con QR o NFC", "Carrito de compras y pedidos", "Pagos online, envíos y seguimiento según la configuración contratada"],
    benefits: ["Ordenás tu oferta y facilitás la decisión de compra", "Podés empezar mostrando productos y crecer hacia una tienda completa", "La herramienta se adapta al nivel de operación de cada negocio"],
  },
  resto: {
    title: "Carta de Menú y Pedidos Resto",
    eyebrow: "SOLUCIÓN DIGITAL PARA GASTRONOMÍA",
    description: "Digitalizá tu carta y recibí pedidos desde la mesa, para Take Away y Delivery, con herramientas que acompañan la operación del restaurante.",
    imageDesk: "/assets/images/calamuchitar/productos/resto_desk.webp",
    imageMobile: "/assets/images/calamuchitar/productos/resto_mobile.webp",
    alt: "Ejemplo de carta digital y pedidos Resto",
    features: ["Carta digital con categorías y productos", "Pedidos desde la mesa mediante QR", "Take Away y Delivery", "Estados del pedido, cocina, caja y comunicación"],
    benefits: ["Reducís errores al tomar pedidos", "Agilizás la atención y la comunicación", "Podés comenzar con una carta y sumar operación cuando la necesites"],
  },
  "turnos-reservas": {
    title: "Turnos y Reservas",
    eyebrow: "ORGANIZÁ TU AGENDA",
    description: "Permití que tus clientes reserven horarios y administrá tu disponibilidad, tus recursos y tus servicios desde un mismo lugar.",
    imageDesk: "/assets/images/calamuchitar/productos/turnos_desk.webp",
    imageMobile: "/assets/images/calamuchitar/productos/turnos_mobile.webp",
    alt: "Ejemplo de turnos y reservas",
    features: ["Horarios y disponibilidad configurables", "Recursos como profesionales, canchas, salas o equipos", "Reservas, cancelaciones y reprogramaciones", "Recordatorios y administración desde tu panel"],
    benefits: ["Evitás cruces y confusiones de horarios", "Tu cliente puede reservar de manera simple", "Se adapta a peluquerías, consultorios, deportes y prestadores"],
  },
  resenias: {
    title: "Tags Reviews (Reseñas de Clientes)",
    eyebrow: "CONVERTÍ EXPERIENCIAS EN CONFIANZA",
    description: "Recibí opiniones, administralas y elegí cuáles mostrar para que nuevos clientes conozcan experiencias reales de tu negocio.",
    imageDesk: "/assets/images/calamuchitar/productos/resenias_desk.webp",
    imageMobile: "/assets/images/calamuchitar/productos/resenias_mobile.webp",
    alt: "Ejemplo de reseñas de clientes",
    features: ["Formulario de reseña configurable", "Reseñas privadas y públicas", "Moderación y selección desde el panel", "Bloque de reseñas públicas en tu Página Web"],
    benefits: ["Generás confianza antes de una compra o reserva", "Elegís qué opiniones representan mejor tu negocio", "Podés gestionar experiencias positivas y las que requieren atención"],
  },
  "beneficios-fidelizacion": {
    title: "Beneficios y Programas de Fidelización",
    eyebrow: "HACÉ QUE TUS CLIENTES VUELVAN",
    description: "Creá propuestas para premiar la frecuencia y fortalecer el vínculo con tus clientes mediante descuentos, puntos, sellos y recompensas.",
    imageDesk: "/assets/images/calamuchitar/productos/beneficios_desk.webp",
    imageMobile: "/assets/images/calamuchitar/productos/beneficios_mobile.webp",
    alt: "Ejemplo de beneficios y recompensas",
    features: ["Programas de puntos, sellos o visitas", "Recompensas y condiciones configurables", "Beneficios privados o públicos", "Seguimiento de movimientos y validación"],
    benefits: ["Premiás la frecuencia y la preferencia", "Podés ofrecer beneficios propios o participar de propuestas regionales", "Transformás una visita ocasional en una nueva oportunidad"],
  },
  chatbot: {
    title: "ChatBot en tu Web",
    eyebrow: "ATENCIÓN DISPONIBLE LAS 24 HORAS",
    description: "Un asistente entrenado con la información real de tu negocio para responder consultas frecuentes, incluso cuando no estás disponible.",
    imageDesk: "/assets/images/calamuchitar/productos/chatbot_desk.webp",
    imageMobile: "/assets/images/calamuchitar/productos/chatbot_mobile.webp",
    alt: "Ejemplo de ChatBot funcionando en una Página Web",
    features: ["Base de conocimiento propia", "Respuestas sobre servicios, horarios y productos", "Widget configurable en color, posición y texto", "Integración en tu Página Web y herramientas públicas"],
    benefits: ["Respondés aunque estés ocupado", "Evitás repetir siempre la misma información", "Ofrecés una primera atención rápida y ordenada"],
  },
  "tags-id": {
    title: "Tags ID - Tarjeta Personal Digital Inteligente",
    eyebrow: "TU IDENTIDAD PROFESIONAL",
    description: "Presentate de manera inteligente y elegante con una tarjeta personal digital que reúne tu información profesional y tus datos de contacto.",
    imageDesk: "/assets/images/calamuchitar/productos/tags_id_desk.webp",
    imageMobile: "/assets/images/calamuchitar/productos/tags_id_mobile.webp",
    alt: "Tags ID, Tarjeta Personal Digital Inteligente",
    features: ["Perfil profesional con tu nombre, actividad y presentación", "Teléfono, WhatsApp, email, redes y enlaces importantes", "Código QR personal y tecnología NFC integrados en una tarjeta física", "Compartí tu perfil digital acercando el celular o leyendo el QR"],
    benefits: ["Una presentación profesional siempre disponible", "Tus datos se actualizan sin cambiar la tarjeta", "Contacto directo en pocos pasos", "Ideal para profesionales, equipos y reuniones"],
  },
  "mi-estadia": {
    title: "Mi Estadía para Alojamientos",
    eyebrow: "LA EXPERIENCIA DEL HUÉSPED",
    description: "Administrá tus reservas y acompañá a tus huéspedes desde la confirmación hasta el final de su estadía, con información y servicios disponibles en un solo lugar.",
    imageDesk: "/assets/images/calamuchitar/productos/miestadia_desk.webp",
    imageMobile: "/assets/images/calamuchitar/productos/miestadia_mobile.webp",
    alt: "Ejemplo de Mi Estadía para alojamientos",
    features: ["Reservas, disponibilidad y datos de los huéspedes", "Pagos, cuenta de la estadía y adicionales", "Pre-checkin, checkin, checkout y comunicaciones", "Información útil, WiFi, reglamento, beneficios y servicios adicionales"],
    benefits: ["Reducís tareas manuales y planillas", "Mantenés informados a tus huéspedes", "Ofrecés una experiencia diferencial desde la reserva", "Todo se administra desde tu panel"],
  },
};
