"use client";

import { useEffect, useMemo, useState } from "react";
import { FaCheck, FaComments, FaListCheck, FaPaperPlane, FaPen, FaPlus, FaTrash, FaUserClock, FaXmark } from "react-icons/fa6";
import TagsSpinner from "@/app/components/TagsSpinner";
import showAlert from "@/app/components/showAlert";
import "./GuestExperienceMessagesManager.css";

const CATEGORY_EMPTY={name:"",code:"",description:"",requiresSchedule:false,isActive:true,sortOrder:0};
const statusText={open:"Pendiente",in_progress:"En curso",resolved:"Resuelta",cancelled:"Cancelada"};
async function read(response){const text=await response.text();if(!text)return{ok:false,error:`Respuesta vacía (${response.status})`};try{return JSON.parse(text)}catch{return{ok:false,error:`Respuesta no válida (${response.status})`}}}
const when=value=>value?new Date(value).toLocaleString("es-AR",{dateStyle:"short",timeStyle:"short"}):"";

export default function GuestExperienceMessagesManager({businessId,data}){
 const base=`businessId=${businessId}&guestAppId=${data.app.id}`,[tab,setTab]=useState("conversations"),[conversations,setConversations]=useState([]),[summary,setSummary]=useState({unread:0,openRequests:0}),[selected,setSelected]=useState(null),[thread,setThread]=useState([]),[reply,setReply]=useState(""),[requests,setRequests]=useState([]),[requestStatus,setRequestStatus]=useState(""),[categories,setCategories]=useState([]),[categoryModal,setCategoryModal]=useState(null),[categoryForm,setCategoryForm]=useState(CATEGORY_EMPTY),[requestAction,setRequestAction]=useState(null),[busy,setBusy]=useState(false);
 async function get(url,silent=false){if(!silent)setBusy(true);try{const response=await fetch(url,{cache:"no-store"}),payload=await read(response);if(!response.ok||!payload.ok){if(!silent)await showAlert({title:"No se pudo cargar",text:payload.error,icon:"error"});return null}return payload}finally{if(!silent)setBusy(false)}}
 async function load(silent=false){const [messagesPayload,requestsPayload,categoriesPayload]=await Promise.all([get(`/api/guest-experience/admin/messages?${base}`,silent),get(`/api/guest-experience/admin/requests?${base}&status=${requestStatus}`,silent),get(`/api/guest-experience/admin/request-categories?${base}`,silent)]);if(messagesPayload){setConversations(messagesPayload.conversations||[]);setSummary(messagesPayload.summary||{})}if(requestsPayload)setRequests(requestsPayload.requests||[]);if(categoriesPayload)setCategories(categoriesPayload.categories||[]);if(selected)await loadThread(selected.stay_id,true)}
 async function loadThread(stayId,silent=false){const payload=await get(`/api/guest-experience/admin/messages?${base}&stayId=${stayId}`,silent);if(payload){setSelected(current=>current?.stay_id===stayId?{...current,...payload.stay}:payload.stay);setThread(payload.messages||[])}}
 useEffect(()=>{load();const timer=setInterval(()=>load(true),10000);return()=>clearInterval(timer)},[requestStatus,selected?.stay_id]);
 async function sendReply(event){event.preventDefault();if(!selected||!reply.trim())return;setBusy(true);try{const response=await fetch("/api/guest-experience/admin/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({businessId,guestAppId:data.app.id,stayId:selected.stay_id||selected.id,message:reply})}),payload=await read(response);if(!response.ok||!payload.ok)return showAlert({title:"No se pudo enviar",text:payload.error,icon:"error"});setReply("");await loadThread(selected.stay_id||selected.id,true);await load(true)}finally{setBusy(false)}}
 async function performRequestChange(item,status,notes=""){setBusy(true);try{const response=await fetch("/api/guest-experience/admin/requests",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({businessId,guestAppId:data.app.id,id:item.id,status,notes})}),payload=await read(response);if(!response.ok||!payload.ok)return showAlert({title:"No se pudo actualizar",text:payload.error,icon:"error"});setRequestAction(null);await load(true);await showAlert({title:"Solicitud actualizada",icon:"success",timer:1200})}finally{setBusy(false)}}
 async function changeRequest(item,status){if(status==="resolved"||status==="cancelled"){setRequestAction({item,status,notes:""});return}const ok=await showAlert({title:"¿Tomar esta solicitud?",text:item.title,icon:"question",showCancelButton:true,confirmButtonText:"Iniciar atención",cancelButtonText:"Volver"});if(ok)await performRequestChange(item,status)}
 function editCategory(item=null){setCategoryForm(item?{id:item.id,name:item.name,code:item.code,description:item.description||"",requiresSchedule:Boolean(Number(item.requires_schedule)),isActive:Boolean(Number(item.is_active)),sortOrder:item.sort_order||0}:CATEGORY_EMPTY);setCategoryModal(true)}
 async function saveCategory(event){event.preventDefault();setBusy(true);try{const response=await fetch("/api/guest-experience/admin/request-categories",{method:categoryForm.id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({businessId,guestAppId:data.app.id,...categoryForm})}),payload=await read(response);if(!response.ok||!payload.ok)return showAlert({title:"No se pudo guardar",text:payload.error,icon:"error"});setCategoryModal(false);await load(true);await showAlert({title:"Tipo guardado",icon:"success",timer:1200})}finally{setBusy(false)}}
 async function removeCategory(item){const ok=await showAlert({title:"¿Eliminar este tipo?",text:item.name,icon:"warning",showCancelButton:true,confirmButtonText:"Eliminar",cancelButtonText:"Cancelar"});if(!ok)return;setBusy(true);try{const response=await fetch("/api/guest-experience/admin/request-categories",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({businessId,guestAppId:data.app.id,id:item.id})}),payload=await read(response);if(!response.ok||!payload.ok)return showAlert({title:"No se pudo eliminar",text:payload.error,icon:"error"});await load(true)}finally{setBusy(false)}}
 const filtered=useMemo(()=>requests,[requests]);
 return <section className="tags_guest_messages_admin"><header><div><span>ATENCIÓN AL HUÉSPED</span><h2>Mensajes y solicitudes</h2><p>Centralizá las consultas y tareas asociadas a cada estadía.</p></div><div className="tags_guest_messages_kpis"><span><strong>{summary.unread||0}</strong> sin leer</span><span><strong>{summary.openRequests||0}</strong> solicitudes activas</span></div></header><nav>{[["conversations","Conversaciones",FaComments],["requests","Solicitudes",FaListCheck],["categories","Tipos de solicitud",FaUserClock]].map(([key,label,Icon])=><button key={key} className={tab===key?"is_active":""} onClick={()=>setTab(key)}><Icon/>{label}</button>)}</nav>
 {tab==="conversations"&&<div className="tags_guest_messages_workspace"><aside>{conversations.map(item=><button key={item.conversation_id} className={selected?.stay_id===item.stay_id?"is_selected":""} onClick={()=>{setSelected(item);loadThread(item.stay_id)}}><div><strong>{item.guest_name}</strong>{Number(item.unread_count)>0&&<b>{item.unread_count}</b>}</div><span>{item.stay_code} · {item.unit_name||"Sin unidad"}</span><p>{item.last_message||"Conversación sin mensajes"}</p><small>{when(item.last_message_at)}</small></button>)}{!conversations.length&&<p className="tags_guest_messages_empty">Todavía no hay conversaciones.</p>}</aside><section>{selected?<><header><div><strong>{selected.guest_name}</strong><span>{selected.stay_code} · {selected.unit_name||"Sin unidad"}</span></div></header><div className="tags_guest_messages_thread">{thread.map(message=><article key={message.id} className={`is_${message.sender_type}`}><span>{message.sender_type==="guest"?selected.guest_name:message.sender_type==="system"?"Actualización":message.sender_name||"Alojamiento"}</span><p>{message.message}</p><small>{when(message.created_at)}</small></article>)}</div><form onSubmit={sendReply}><textarea required value={reply} onChange={event=>setReply(event.target.value)} placeholder="Escribí una respuesta…"/><button disabled={busy||!reply.trim()}><FaPaperPlane/> Enviar</button></form></>:<div className="tags_guest_messages_blank"><FaComments/><strong>Seleccioná una conversación</strong><span>El historial completo aparecerá acá.</span></div>}</section></div>}
 {tab==="requests"&&<><div className="tags_guest_request_filters"><label>Estado<select value={requestStatus} onChange={event=>setRequestStatus(event.target.value)}><option value="">Todas</option><option value="open">Pendientes</option><option value="in_progress">En curso</option><option value="resolved">Resueltas</option><option value="cancelled">Canceladas</option></select></label></div><div className="tags_guest_request_cards">{filtered.map(item=><article key={item.id}><header><h3>{item.category_name}</h3><span className={`is_${item.status}`}>{statusText[item.status]||item.status}</span></header><p>{item.details||"Sin detalle adicional."}</p><dl><div><dt>Huésped</dt><dd>{item.guest_name}</dd></div><div><dt>Estadía</dt><dd>{item.stay_code} · {item.unit_name||"Sin unidad"}</dd></div>{item.requested_for&&<div><dt>Fecha y hora preferida</dt><dd>{when(item.requested_for)}</dd></div>}<div><dt>Enviada</dt><dd>{when(item.created_at)}</dd></div></dl>{item.resolution_notes&&<blockquote>{item.resolution_notes}</blockquote>}<footer>{item.status==="open"&&<button onClick={()=>changeRequest(item,"in_progress")}><FaUserClock/> Atender solicitud</button>}{["open","in_progress"].includes(item.status)&&<button className="is_success" onClick={()=>changeRequest(item,"resolved")}><FaCheck/> Resolver</button>}{["open","in_progress"].includes(item.status)&&<button className="is_danger" onClick={()=>changeRequest(item,"cancelled")}><FaXmark/> Cancelar</button>}</footer></article>)}{!filtered.length&&<p className="tags_guest_messages_empty">No hay solicitudes para este filtro.</p>}</div></>}
 {tab==="categories"&&<><div className="tags_guest_categories_toolbar"><p>Definí qué puede pedir el huésped y si debe elegir fecha y hora.</p><button onClick={()=>editCategory()}><FaPlus/> Nuevo tipo</button></div><div className="tags_guest_categories_list">{categories.map(item=><article key={item.id}><div><strong>{item.name}</strong><span>{item.description||"Sin descripción"}</span><small>{item.requires_schedule?"Requiere fecha y hora":"Sin programación"} · {item.is_active?"Visible":"Oculto"}</small></div><footer><button title="Editar" onClick={()=>editCategory(item)}><FaPen/></button><button title="Eliminar" onClick={()=>removeCategory(item)}><FaTrash/></button></footer></article>)}</div></>}
 {requestAction&&<div className="tags_guest_category_backdrop" onMouseDown={()=>!busy&&setRequestAction(null)}><section className="tags_guest_category_modal tags_guest_request_action_modal" onMouseDown={event=>event.stopPropagation()}><header><div><h3>{requestAction.status==="resolved"?"Resolver solicitud":"Cancelar solicitud"}</h3><small>{requestAction.item.title}</small></div><button onClick={()=>setRequestAction(null)} aria-label="Cerrar"><FaXmark/></button></header><form onSubmit={event=>{event.preventDefault();performRequestChange(requestAction.item,requestAction.status,requestAction.notes)}}><label className="is_wide">Observación para el huésped<textarea value={requestAction.notes} onChange={event=>setRequestAction({...requestAction,notes:event.target.value})} placeholder="Opcional: explicá cómo se resolvió o por qué se cancela"/></label><button disabled={busy}>{requestAction.status==="resolved"?"Confirmar resolución":"Confirmar cancelación"}</button></form></section></div>}{categoryModal&&<div className="tags_guest_category_backdrop" onMouseDown={()=>!busy&&setCategoryModal(false)}><section className="tags_guest_category_modal" onMouseDown={event=>event.stopPropagation()}><header><h3>{categoryForm.id?"Editar tipo":"Nuevo tipo de solicitud"}</h3><button onClick={()=>setCategoryModal(false)} aria-label="Cerrar"><FaXmark/></button></header><form onSubmit={saveCategory}><label>Nombre<input required value={categoryForm.name} onChange={event=>setCategoryForm({...categoryForm,name:event.target.value})}/></label><label>Código interno<input required disabled={Boolean(categoryForm.id)} value={categoryForm.code} onChange={event=>setCategoryForm({...categoryForm,code:event.target.value})} placeholder="ej. desayuno"/></label><label className="is_wide">Descripción<textarea value={categoryForm.description} onChange={event=>setCategoryForm({...categoryForm,description:event.target.value})}/></label><label>Orden<input type="number" value={categoryForm.sortOrder} onChange={event=>setCategoryForm({...categoryForm,sortOrder:event.target.value})}/></label><label className="is_check"><input type="checkbox" checked={categoryForm.requiresSchedule} onChange={event=>setCategoryForm({...categoryForm,requiresSchedule:event.target.checked})}/> Pedir fecha y hora</label><label className="is_check"><input type="checkbox" checked={categoryForm.isActive} onChange={event=>setCategoryForm({...categoryForm,isActive:event.target.checked})}/> Visible para huéspedes</label><button disabled={busy}>Guardar</button></form></section></div>}{busy&&<TagsSpinner size={110} logoSize={58} borderSize={5} background="rgba(255,255,255,.72)"/>}</section>;
}
