"use client";

import { useEffect, useMemo, useState } from "react";
import { FaCalendarCheck, FaCheck, FaClock, FaFloppyDisk } from "react-icons/fa6";
import TagsSpinner from "@/app/components/TagsSpinner";
import showAlert from "@/app/components/showAlert";
import "./GuestExperienceTurnosManager.css";
import "./GuestExperienceTurnosServiceReservations.css";

async function read(response){const text=await response.text();if(!text)return{ok:false,error:`Respuesta vacía (${response.status})`};try{return JSON.parse(text)}catch{return{ok:false,error:`Respuesta no válida (${response.status})`}}}
const when=value=>value?new Date(value).toLocaleString("es-AR",{dateStyle:"short",timeStyle:"short"}):"";
const day=value=>{const date=new Date(value),offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,10)};
const today=()=>day(new Date());
const tomorrow=()=>{const value=new Date();value.setDate(value.getDate()+1);return day(value)};
const STATUS={pending:"Pendiente",confirmed:"Confirmada",checked_in:"Llegó",in_progress:"En curso",completed:"Finalizada",cancelled:"Cancelada",rejected:"Rechazada"};

export default function GuestExperienceTurnosManager({businessId,data}){
 const[state,setState]=useState({services:[],bookings:[],resources:[],operationalBookings:[]}),[selected,setSelected]=useState([]),[busy,setBusy]=useState(false),[tab,setTab]=useState("configuration"),[period,setPeriod]=useState("all"),base=`businessId=${businessId}&guestAppId=${data.app.id}`;
 async function load(){setBusy(true);try{const response=await fetch(`/api/guest-experience/admin/turnos?${base}`,{cache:"no-store"}),payload=await read(response);if(!response.ok||!payload.ok)return showAlert({title:"No se pudo cargar",text:payload.error,icon:"error"});setState(payload);setSelected(payload.services.filter(item=>Number(item.selected)===1).map(item=>`${item.turnos_id}:${item.service_id}`))}finally{setBusy(false)}}
 useEffect(()=>{load()},[]);
 function toggle(item){const key=`${item.turnos_id}:${item.service_id}`;setSelected(current=>current.includes(key)?current.filter(value=>value!==key):[...current,key])}
 async function save(){setBusy(true);try{const services=state.services.filter(item=>selected.includes(`${item.turnos_id}:${item.service_id}`)).map((item,index)=>({turnosId:item.turnos_id,serviceId:item.service_id,sortOrder:index})),response=await fetch("/api/guest-experience/admin/turnos",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({businessId,guestAppId:data.app.id,services})}),payload=await read(response);if(!response.ok||!payload.ok)return showAlert({title:"No se pudo guardar",text:payload.error,icon:"error"});await load();await showAlert({title:"Servicios actualizados",icon:"success",timer:1400})}finally{setBusy(false)}}
 const groups=useMemo(()=>Object.values(state.services.reduce((all,item)=>{(all[item.turnos_id]??={id:item.turnos_id,name:item.turnos_name,items:[]}).items.push(item);return all},{})),[state.services]);
 const enabledServices=useMemo(()=>state.services.filter(item=>Number(item.selected)===1),[state.services]);
 const activeServiceId=tab.startsWith("service:")?Number(tab.split(":")[1]):0;
 const visibleForPeriod=item=>period==="all"||day(item.starts_at)===(period==="today"?today():tomorrow());
 return <section className="tags_guest_turnos_admin"><header><div><span>SERVICIOS PARA HUÉSPEDES</span><h2>Reservas de Tags Turnos</h2><p>Elegí qué servicios se muestran en Mi Estadía y consultá las reservas realizadas.</p></div></header><nav><button className={tab==="configuration"?"is_active":""} onClick={()=>setTab("configuration")}><FaCalendarCheck/> Servicios disponibles</button><button className={tab==="bookings"?"is_active":""} onClick={()=>setTab("bookings")}><FaClock/> Reservas de huéspedes</button>{enabledServices.map(item=><button key={item.service_id} className={activeServiceId===Number(item.service_id)?"is_active":""} onClick={()=>{setTab(`service:${item.service_id}`);setPeriod("all")}}><FaCalendarCheck/> {item.service_name}</button>)}</nav>
 {tab==="configuration"&&<><div className="tags_guest_turnos_instances">{groups.map(group=><section key={group.id}><header><h3>{group.name}</h3></header><div>{group.items.map(item=>{const active=selected.includes(`${item.turnos_id}:${item.service_id}`);return <button type="button" className={active?"is_selected":""} key={item.service_id} onClick={()=>toggle(item)}><span>{active?<FaCheck/>:<i/>}</span><div><strong>{item.service_name}</strong><small>{item.duration_minutes} minutos · {item.booking_mode==="rental"?"Alquiler":"Turno"}</small>{item.description&&<p>{item.description}</p>}</div></button>})}</div></section>)}{!groups.length&&<p>No hay instancias de Tags Turnos con servicios disponibles.</p>}</div><footer className="tags_guest_turnos_save"><button onClick={save} disabled={busy}><FaFloppyDisk/> Guardar servicios</button></footer></>}
 {tab==="bookings"&&<div className="tags_guest_turnos_admin_bookings"><div className="is_header"><span>Reserva</span><span>Huésped / estadía</span><span>Servicio</span><span>Horario</span><span>Estado</span></div>{state.bookings.map(item=><article key={item.booking_id}><strong>{item.booking_number}</strong><span>{item.guest_name}<small>{item.stay_code} · {item.unit_name||"Sin unidad"}</small></span><span>{item.service_name}<small>{item.resource_names||item.turnos_name}</small></span><span>{when(item.starts_at)}<small>hasta {when(item.ends_at)}</small></span><b className={`is_${item.status}`}>{STATUS[item.status]||item.status}</b></article>)}{!state.bookings.length&&<p>No hay reservas de servicios realizadas desde Mi Estadía.</p>}</div>}
 {activeServiceId>0&&<ServiceReservations service={enabledServices.find(item=>Number(item.service_id)===activeServiceId)} resources={state.resources.filter(item=>Number(item.service_id)===activeServiceId)} bookings={state.operationalBookings.filter(item=>Number(item.service_id)===activeServiceId)} period={period} onPeriod={setPeriod} visibleForPeriod={visibleForPeriod}/>} {busy&&<TagsSpinner size={110} logoSize={58} borderSize={5} background="rgba(255,255,255,.72)"/>}</section>;
}

function ServiceReservations({service,resources,bookings,period,onPeriod,visibleForPeriod}){
 const count=scope=>bookings.filter(item=>scope==="all"||day(item.starts_at)===(scope==="today"?today():tomorrow())).length;
 return <div className="tags_guest_turnos_service_reservations"><header><div><span>RESERVAS POR RECURSO</span><h3>{service?.service_name}</h3><p>Visualizá la operación de cada recurso asociado al servicio.</p></div><nav>{[["all","Todas"],["today","Hoy"],["tomorrow","Mañana"]].map(([key,label])=><button key={key} className={period===key?"is_active":""} onClick={()=>onPeriod(key)}><strong>{count(key)}</strong><span>{label}</span></button>)}</nav></header><section>{resources.map(resource=>{const resourceBookings=bookings.filter(item=>Number(item.resource_id)===Number(resource.resource_id)&&visibleForPeriod(item));return <article key={resource.resource_id}><header><div><h4>{resource.resource_name}</h4><span>Capacidad: {resource.capacity}</span></div><b>{resourceBookings.length} reserva{resourceBookings.length===1?"":"s"}</b></header><div>{resourceBookings.map(item=><section key={`${item.booking_id}:${item.resource_id}`}><div><strong>{item.booking_number} · {item.guest_name||item.customer_name}</strong><span>{item.stay_code?`${item.stay_code} · ${item.unit_name||"Sin unidad"}`:item.customer_email||item.customer_phone||"Cliente de Turnos"}</span></div><div><strong>{when(item.starts_at)}</strong><small>hasta {when(item.ends_at)} · {item.units||item.party_size||1} plaza{Number(item.units||item.party_size||1)===1?"":"s"}</small></div><b className={`is_${item.status}`}>{STATUS[item.status]||item.status}</b></section>)}{!resourceBookings.length&&<p>No hay reservas para este período.</p>}</div></article>})}{!resources.length&&<p>Este servicio no tiene recursos asociados.</p>}</section></div>;
}
