"use client";
import {useEffect,useMemo,useState} from "react";
import {FaDownload,FaEye,FaLink,FaPause,FaPen,FaPlay,FaPlus,FaQrcode,FaTrash,FaXmark} from "react-icons/fa6";
import TagsSpinner from "@/app/components/TagsSpinner";
import showAlert from "@/app/components/showAlert";
import "./QrAgencyQrs.css";
const EMPTY={assignmentId:0,customerId:"",label:"",finalUrl:"",status:"active",stopMessage:"Este código QR está temporalmente fuera de servicio."};
async function resultOf(r){const t=await r.text();if(!t)return{};try{return JSON.parse(t)}catch{return{}}}
export default function QrAgencyQrs({businessId,onChanged}){
 const[data,setData]=useState({qrs:[],customers:[],usage:{}}),[busy,setBusy]=useState(false),[modal,setModal]=useState(false),[preview,setPreview]=useState(null),[form,setForm]=useState(EMPTY),[customerFilter,setCustomerFilter]=useState(""),[statusFilter,setStatusFilter]=useState("");
 async function load(){setBusy(true);try{const r=await fetch(`/api/qr-agency/admin/qrs?businessId=${businessId}`,{cache:"no-store"}),p=await resultOf(r);if(!r.ok)throw new Error(p.error||"No se pudieron cargar los QRs");setData(p)}catch(e){await showAlert({title:"No se pudieron cargar los QRs",text:e.message,icon:"error"})}finally{setBusy(false)}}
 useEffect(()=>{load()},[businessId]);
 const filtered=useMemo(()=>data.qrs.filter(x=>(!customerFilter||String(x.customer_id)===customerFilter)&&(!statusFilter||x.assignment_status===statusFilter)),[data.qrs,customerFilter,statusFilter]);
 function open(x=null){setForm(x?{assignmentId:x.assignment_id,customerId:String(x.customer_id),label:x.label||"",finalUrl:x.final_url||"",status:x.assignment_status,stopMessage:x.stop_message||EMPTY.stopMessage}:{...EMPTY,customerId:data.customers[0]?String(data.customers[0].id):""});setModal(true)}
 async function save(e){e.preventDefault();setBusy(true);try{const r=await fetch("/api/qr-agency/admin/qrs",{method:form.assignmentId?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({businessId,...form})}),p=await resultOf(r);if(!r.ok)throw new Error(p.error||"No se pudo guardar el QR");setModal(false);await load();await onChanged?.();await showAlert({title:form.assignmentId?"QR actualizado":"QR creado y asignado",icon:"success",timer:1300})}catch(e){await showAlert({title:"No se pudo guardar",text:e.message,icon:"error"})}finally{setBusy(false)}}
 async function changeStatus(x){const status=x.assignment_status==="active"?"paused":"active",ok=await showAlert({title:status==="paused"?"¿Pausar este QR?":"¿Reactivar este QR?",text:status==="paused"?"Al escanearlo se mostrará el aviso de pausa.":"Volverá a dirigir al destino configurado.",icon:"question",showCancelButton:true,confirmButtonText:status==="paused"?"Pausar":"Reactivar",cancelButtonText:"Cancelar"});if(!ok)return;setBusy(true);try{const r=await fetch("/api/qr-agency/admin/qrs",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({businessId,assignmentId:x.assignment_id,customerId:x.customer_id,label:x.label,finalUrl:x.final_url,status,stopMessage:x.stop_message||EMPTY.stopMessage})}),p=await resultOf(r);if(!r.ok)throw new Error(p.error||"No se pudo cambiar el estado");await load();await onChanged?.()}catch(e){await showAlert({title:"No se pudo cambiar el estado",text:e.message,icon:"error"})}finally{setBusy(false)}}
 async function archive(x){const ok=await showAlert({title:"¿Archivar este QR?",text:"Dejará de funcionar y liberará un lugar del cupo. Sus estadísticas se conservarán.",icon:"warning",showCancelButton:true,confirmButtonText:"Archivar",cancelButtonText:"Cancelar"});if(!ok)return;setBusy(true);try{const r=await fetch("/api/qr-agency/admin/qrs",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({businessId,assignmentId:x.assignment_id})}),p=await resultOf(r);if(!r.ok)throw new Error(p.error||"No se pudo archivar");await load();await onChanged?.();await showAlert({title:"QR archivado",icon:"success",timer:1200})}catch(e){await showAlert({title:"No se pudo archivar",text:e.message,icon:"error"})}finally{setBusy(false)}}
 return <section className="tags_qra_qrs">{busy&&<TagsSpinner size={110} logoSize={56} borderSize={4} background="rgba(247,250,248,.82)"/>}<header><div><FaQrcode/><span><h2>Códigos QR</h2><p>Creá, asigná y administrá los destinos de tus clientes.</p></span></div><button onClick={()=>open()} disabled={!data.customers.length||Number(data.usage.used)>=Number(data.usage.limit)}><FaPlus/> Nuevo QR</button></header><div className="tags_qra_qrs_tools"><strong>{Number(data.usage.used||0)} de {Number(data.usage.limit||0)} utilizados</strong><label>Cliente<select value={customerFilter} onChange={e=>setCustomerFilter(e.target.value)}><option value="">Todos</option>{data.customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Estado<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Todos</option><option value="active">Activos</option><option value="paused">Pausados</option></select></label></div>
 {!data.customers.length?<p className="tags_qra_qrs_empty">Primero creá al menos un cliente.</p>:!filtered.length?<p className="tags_qra_qrs_empty">Todavía no hay QRs para mostrar.</p>:<div className="tags_qra_qrs_grid">{filtered.map(x=><article key={x.assignment_id}><div className="tags_qra_qrs_identity"><img src={`/api/qr/download/${x.code}?format=svg&preview=1`} alt={`QR ${x.code}`}/><span><b>{x.label}</b><code>{x.code}</code></span><em className={x.assignment_status}>{x.assignment_status==="active"?"Activo":"Pausado"}</em></div><p><strong>{x.customer_name}</strong><small>{x.customer_email}</small></p><a href={x.final_url} target="_blank" rel="noreferrer"><FaLink/> {x.final_url}</a><div className="tags_qra_qrs_stats"><span><b>{Number(x.total_clicks||0)}</b> escaneos</span><span>Último: {x.last_click_at?new Date(x.last_click_at).toLocaleString("es-AR"):"sin actividad"}</span></div><footer><button title="Vista previa" onClick={()=>setPreview(x)}><FaEye/></button><a title="Descargar SVG" href={`/api/qr/download/${x.code}?format=svg`}><FaDownload/></a><button title="Editar" onClick={()=>open(x)}><FaPen/></button><button title={x.assignment_status==="active"?"Pausar":"Reactivar"} onClick={()=>changeStatus(x)}>{x.assignment_status==="active"?<FaPause/>:<FaPlay/>}</button><button className="danger" title="Archivar" onClick={()=>archive(x)}><FaTrash/></button></footer></article>)}</div>}
 {modal&&<div className="tags_qra_qrs_overlay"><form className="tags_qra_qrs_modal" onSubmit={save}><header><div><FaQrcode/><span><h3>{form.assignmentId?"Editar QR":"Nuevo QR"}</h3><p>El código impreso no cambia al modificar el destino.</p></span></div><button type="button" onClick={()=>setModal(false)}><FaXmark/></button></header><label>Cliente<select required value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value})}>{data.customers.map(c=><option key={c.id} value={c.id}>{c.name} · {c.email}</option>)}</select></label><label>Nombre del QR<input required value={form.label} onChange={e=>setForm({...form,label:e.target.value})} placeholder="Ej.: Carta del restaurante"/></label><label>Destino final<input required type="url" value={form.finalUrl} onChange={e=>setForm({...form,finalUrl:e.target.value})} placeholder="https://..."/></label>{form.assignmentId>0&&<label>Estado<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Activo</option><option value="paused">Pausado</option></select></label>}{form.status==="paused"&&<label>Mensaje de pausa<textarea required value={form.stopMessage} onChange={e=>setForm({...form,stopMessage:e.target.value})}/></label>}<footer><button type="button" onClick={()=>setModal(false)}>Cancelar</button><button type="submit">Guardar</button></footer></form></div>}
 {preview&&<div className="tags_qra_qrs_overlay"><section className="tags_qra_qrs_preview"><button onClick={()=>setPreview(null)}><FaXmark/></button><img src={`/api/qr/download/${preview.code}?format=svg&preview=1`} alt={`QR ${preview.code}`}/><h3>{preview.label}</h3><code>{preview.code}</code><a href={`/api/qr/download/${preview.code}?format=png`}><FaDownload/> Descargar PNG</a></section></div>}</section>
}
