"use client";

import { useEffect, useState } from "react";
import { FaEnvelope, FaPen, FaPlus, FaTrash, FaUserCheck, FaUserSlash, FaXmark } from "react-icons/fa6";
import TagsSpinner from "@/app/components/TagsSpinner";
import showAlert from "@/app/components/showAlert";
import "./QrAgencyCustomers.css";

const EMPTY = { name: "", email: "", phone: "", notes: "", status: "active" };
async function json(response) { const text = await response.text(); try { return text ? JSON.parse(text) : {}; } catch { return {}; } }

export default function QrAgencyCustomers({ businessId, onChanged }) {
    const [customers, setCustomers] = useState([]), [busy, setBusy] = useState(false), [modal, setModal] = useState(false), [form, setForm] = useState(EMPTY), [editing, setEditing] = useState(null);
    async function load() { setBusy(true); try { const response = await fetch(`/api/qr-agency/admin/customers?businessId=${businessId}`, { cache: "no-store" }), data = await json(response); if (!response.ok) throw new Error(data.error || "No se pudieron cargar los clientes"); setCustomers(data.customers || []); } catch (error) { await showAlert({ title: "No se pudo cargar", text: error.message, icon: "error" }); } finally { setBusy(false); } }
    useEffect(() => { load(); }, [businessId]);
    function open(item = null) { setEditing(item?.id || null); setForm(item ? { name: item.name || "", email: item.email || "", phone: item.phone || "", notes: item.notes || "", status: item.status || "active" } : EMPTY); setModal(true); }
    async function save(event) { event.preventDefault(); setBusy(true); try { const response = await fetch("/api/qr-agency/admin/customers", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ businessId, customerId: editing, ...form }) }), data = await json(response); if (!response.ok) throw new Error(data.error || "No se pudo guardar"); setModal(false); await load(); onChanged?.(); await showAlert({ title: editing ? "Cliente actualizado" : "Cliente creado", icon: "success", timer: 1300 }); } catch (error) { await showAlert({ title: "No se pudo guardar", text: error.message, icon: "error" }); } finally { setBusy(false); } }
    async function toggle(item) { const next = item.status === "active" ? "suspended" : "active", ok = await showAlert({ title: next === "active" ? "¿Reactivar cliente?" : "¿Suspender cliente?", text: next === "active" ? "Podrá volver a solicitar acceso." : "Sus sesiones activas serán revocadas.", icon: "warning", showCancelButton: true, confirmButtonText: next === "active" ? "Reactivar" : "Suspender", cancelButtonText: "Cancelar" }); if (!ok) return; setBusy(true); try { const response = await fetch("/api/qr-agency/admin/customers", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ businessId, customerId: item.id, name: item.name, email: item.email, phone: item.phone, notes: item.notes, status: next }) }), data = await json(response); if (!response.ok) throw new Error(data.error); await load(); onChanged?.(); } catch (error) { await showAlert({ title: "No se pudo completar", text: error.message, icon: "error" }); } finally { setBusy(false); } }
    async function archive(item) { const ok = await showAlert({ title: "¿Archivar cliente?", text: "Dejará de aparecer en el listado y se revocarán sus accesos.", icon: "warning", showCancelButton: true, confirmButtonText: "Archivar", cancelButtonText: "Cancelar" }); if (!ok) return; setBusy(true); try { const response = await fetch("/api/qr-agency/admin/customers", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ businessId, customerId: item.id }) }), data = await json(response); if (!response.ok) throw new Error(data.error); await load(); onChanged?.(); } catch (error) { await showAlert({ title: "No se pudo archivar", text: error.message, icon: "error" }); } finally { setBusy(false); } }
    async function send(item) { const ok = await showAlert({ title: "¿Enviar acceso?", text: `Se enviará un magic link a ${item.email}.`, icon: "question", showCancelButton: true, confirmButtonText: "Enviar enlace", cancelButtonText: "Cancelar" }); if (!ok) return; setBusy(true); try { const response = await fetch("/api/qr-agency/admin/customers/send-access", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ businessId, customerId: item.id }) }), data = await json(response); if (!response.ok) throw new Error(data.error); await showAlert({ title: "Acceso enviado", text: `Enviamos el enlace a ${item.email}.`, icon: "success" }); } catch (error) { await showAlert({ title: "No se pudo enviar", text: error.message, icon: "error" }); } finally { setBusy(false); } }
    return <section className="tags_qr_agency_customers">{busy && <TagsSpinner size={110} logoSize={58} borderSize={5} background="rgba(247,250,248,.82)" />}<header><div><h2>Clientes de la agencia</h2><p>Administrá quién accede y cuántos códigos QR tiene asignados.</p></div><button type="button" onClick={() => open()}><FaPlus /> Nuevo cliente</button></header><div className="tags_qr_agency_customers_list">{customers.map(item => <article key={item.id}><div><span className={`is_${item.status}`}>{item.status === "active" ? "Activo" : "Suspendido"}</span><h3>{item.name}</h3><a href={`mailto:${item.email}`}>{item.email}</a>{item.phone && <small>{item.phone}</small>}</div><dl><div><dt>QR asignados</dt><dd>{Number(item.qr_count || 0)}</dd></div><div><dt>Último acceso</dt><dd>{item.last_access_at ? new Date(item.last_access_at).toLocaleString("es-AR") : "Nunca"}</dd></div></dl><nav><button type="button" title="Enviar acceso" disabled={item.status !== "active"} onClick={() => send(item)}><FaEnvelope /></button><button type="button" title="Editar" onClick={() => open(item)}><FaPen /></button><button type="button" title={item.status === "active" ? "Suspender" : "Reactivar"} onClick={() => toggle(item)}>{item.status === "active" ? <FaUserSlash /> : <FaUserCheck />}</button><button type="button" className="danger" title="Archivar" onClick={() => archive(item)}><FaTrash /></button></nav></article>)}{!customers.length && !busy && <p className="tags_qr_agency_customers_empty">Todavía no cargaste clientes.</p>}</div>{modal && <div className="tags_qr_agency_customer_modal"><form onSubmit={save}><header><div><small>QR AGENCY</small><h2>{editing ? "Editar cliente" : "Nuevo cliente"}</h2></div><button type="button" aria-label="Cerrar" onClick={() => setModal(false)}><FaXmark /></button></header><div className="tags_qr_agency_customer_form"><label>Nombre *<input required value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} /></label><label>Email *<input required type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} /></label><label>Teléfono<input inputMode="tel" value={form.phone} onChange={event => setForm({ ...form, phone: event.target.value })} /></label><label>Estado<select value={form.status} onChange={event => setForm({ ...form, status: event.target.value })}><option value="active">Activo</option><option value="suspended">Suspendido</option></select></label><label className="wide">Observaciones<textarea rows="4" value={form.notes} onChange={event => setForm({ ...form, notes: event.target.value })} /></label></div><footer><button type="button" onClick={() => setModal(false)}>Cancelar</button><button type="submit">Guardar cliente</button></footer></form></div>}</section>;
}
