import { useMemo } from "react";

const MONTHS = ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"];

export default function PlanModalCalendar({ form, setForm, editing, addons, sites, prices, onClose, onSubmit }) {
  const set = (field, value) => setForm(valueState => ({ ...valueState, [field]: value }));
  const planPrices = prices.filter(price => Number(price.plan_id) === Number(editing));
  const calendarMonthly = Array.from({ length: 12 }, (_, index) => String(planPrices.find(price => Number(price.calendar_month) === index + 1 && price.billing_mode === "manual")?.amount || ""));
  const monthly = useMemo(() => form.monthly.some(value => value !== "") ? form.monthly : calendarMonthly.some(value => value !== "") ? calendarMonthly : form.durationPrices, [form.monthly, form.durationPrices, calendarMonthly]);
  const annualValue = form.pack12 || form.durationPrices[11] || planPrices.find(price => Number(price.duration_months) === 12 && !price.calendar_month && price.billing_mode === "manual")?.amount || "";
  const recurringValue = form.recurring || planPrices.find(price => price.billing_mode === "recurring")?.amount || "";
  const directory = ["directory_web", "directory_web_plus"].includes(form.code);
  const updateMonthly = (index, value) => set("monthly", monthly.map((item, itemIndex) => itemIndex === index ? value : item));
  return <div className="tags_subscription_modal_backdrop" onMouseDown={onClose}><section className="tags_subscription_modal" onMouseDown={event => event.stopPropagation()}><header><h2>{editing ? "Editar plan" : "Nuevo plan"}</h2><button type="button" onClick={onClose}>×</button></header><form onSubmit={onSubmit}><div className="tags_subscription_form_grid">
    <label>Nombre<input required value={form.name} onChange={event => set("name", event.target.value)} /></label><label>Código<input value={form.code} disabled={Boolean(editing)} onChange={event => set("code", event.target.value)} /></label><label className="is_wide">Descripción<textarea value={form.description} onChange={event => set("description", event.target.value)} /></label>
    <label>Cupo de QRs<input type="number" min="0" value={form.maxQrCodes} onChange={event => set("maxQrCodes", event.target.value)} /></label><label>Visibilidad<select value={form.visibility} onChange={event => set("visibility", event.target.value)}><option value="public">Público</option><option value="private">Privado</option></select></label>{directory && <label>Directorio<select required value={form.siteId} onChange={event => set("siteId", event.target.value)}><option value="">Seleccionar directorio</option>{sites.map(site => <option key={site.id} value={site.id}>{site.name}</option>)}</select></label>}
    <div className="is_wide"><strong>Precios por mes calendario</strong><div className="tags_subscription_month_grid">{monthly.map((value, index) => <label key={index}>{MONTHS[index]}<input type="number" min="0" value={value} onChange={event => updateMonthly(index, event.target.value)} /></label>)}</div><div className="tags_subscription_form_grid"><label>Promo anual (12 meses)<input type="number" min="0" value={annualValue} onChange={event => set("pack12", event.target.value)} /></label><label>Suscripción mensual Mercado Pago<input type="number" min="0" value={recurringValue} onChange={event => set("recurring", event.target.value)} /></label></div></div>
    <label className="tags_subscription_check"><input type="checkbox" checked={Boolean(form.isActive)} onChange={event => set("isActive", event.target.checked)} /><span>Plan activo</span></label><label className="tags_subscription_check"><input type="checkbox" checked={Boolean(form.isFree)} onChange={event => set("isFree", event.target.checked)} /><span>Plan gratuito</span></label>
    {addons.length > 0 && <div className="is_wide"><strong>Herramientas incluidas</strong>{addons.map(addon => <label className="tags_subscription_check" key={addon.code}><input type="checkbox" checked={Number(form.addons[addon.code] || 0) > 0} onChange={event => set("addons", { ...form.addons, [addon.code]: event.target.checked ? Math.max(1, Number(form.addons[addon.code] || 1)) : 0 })} /><span>{addon.name}</span></label>)}</div>}
  </div><footer><button type="button" onClick={onClose}>Cancelar</button><button type="submit">{editing ? "Guardar cambios" : "Crear plan"}</button></footer></form></section></div>;
}
