"use client";

import { useEffect, useState } from "react";
import { FaChartLine, FaDownload, FaLink, FaPen, FaQrcode, FaXmark } from "react-icons/fa6";
import TagsSpinner from "@/app/components/TagsSpinner";
import TimelineChart from "@/app/components/stats/TimeLineChart";
import QrsClicks from "@/app/components/stats/QrsClicks";
import showAlert from "@/app/components/showAlert";
import "./QrAgencyCustomerPanel.css";
import "./QrAgencyCustomerAnalytics.css";

const MSG = "Este código QR está temporalmente fuera de servicio.";
const EMPTY_STATS = { summary: {}, timeline: [], qrStats: [], geo: { countries: [], provinces: [], cities: [] }, devices: [] };
async function payload(response) { const text = await response.text(); try { return text ? JSON.parse(text) : {}; } catch { return {}; } }

export default function QrAgencyCustomerPanel({ agencySlug, customerName }) {
    const [data, setData] = useState({ qrs: [] });
    const [stats, setStats] = useState(EMPTY_STATS);
    const [statsEnabled, setStatsEnabled] = useState(null);
    const [days, setDays] = useState("30");
    const [qrId, setQrId] = useState("all");
    const [busy, setBusy] = useState(true);
    const [form, setForm] = useState(null);
    async function load() { setBusy(true); try { const response = await fetch(`/agency/${agencySlug}/api/qrs`, { cache: "no-store" }); const result = await payload(response); if (response.status === 401) { location.href = `/agency/${agencySlug}/login?error=session_expired`; return; } if (!response.ok) throw new Error(result.error || "No se pudieron cargar tus QRs"); setData(result); } catch (error) { await showAlert({ title: "No se pudieron cargar tus QRs", text: error.message, icon: "error" }); } finally { setBusy(false); } }
    async function loadStats() { try { const params = new URLSearchParams({ days }); if (qrId !== "all") params.set("qrId", qrId); const response = await fetch(`/agency/${agencySlug}/api/stats?${params}`, { cache: "no-store" }); const result = await payload(response); if (response.status === 401) { location.href = `/agency/${agencySlug}/login?error=session_expired`; return; } if (result.disabled) { setStatsEnabled(false); return; } if (!response.ok) throw new Error(result.error || "No se pudieron cargar las estadísticas"); setStatsEnabled(true); setStats(result.stats || EMPTY_STATS); } catch (error) { setStatsEnabled(false); console.error("QR Agency customer stats error", error); } }
    useEffect(() => { load(); }, [agencySlug]);
    useEffect(() => { loadStats(); }, [agencySlug, days, qrId]);
    async function save(event) { event.preventDefault(); setBusy(true); try { const response = await fetch(`/agency/${agencySlug}/api/qrs`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const result = await payload(response); if (!response.ok) throw new Error(result.error || "No se pudo guardar"); setForm(null); await load(); await showAlert({ title: "QR actualizado", icon: "success", timer: 1300 }); } catch (error) { await showAlert({ title: "No se pudo guardar", text: error.message, icon: "error" }); } finally { setBusy(false); } }
    function edit(item) { setForm({ assignmentId: item.assignment_id, label: item.label || "", finalUrl: item.final_url || "", status: item.assignment_status, stopMessage: item.stop_message || MSG, browserGeolocationEnabled: Number(item.browser_geolocation_enabled) === 1 }); }
    return <main className="tags_qrac">
        {busy && <TagsSpinner size={120} logoSize={64} borderSize={5} background="rgba(245,249,246,.86)" />}
        <header><FaQrcode /><div><small>PANEL PRIVADO</small><h1>Mis códigos QR</h1><p>Hola <strong>{data.customer?.name || customerName}</strong>. Administrá tus destinos sin volver a imprimir tus códigos.</p></div></header>
        {!busy && !data.qrs.length ? <section className="tags_qrac_empty"><FaQrcode /><h2>Todavía no tenés QRs asignados</h2><p>Contactá a tu agencia para solicitar un código.</p></section> : <section className="tags_qrac_grid">{data.qrs.map(item => <article key={item.assignment_id}><div className="tags_qrac_image"><img src={`/api/qr/download/${item.code}?format=svg&preview=1`} alt={`QR ${item.code}`} /><em className={item.assignment_status}>{item.assignment_status === "active" ? "Activo" : "Pausado"}</em></div><h2>{item.label}</h2><code>{item.code}</code><a href={item.final_url} target="_blank" rel="noreferrer"><FaLink />{item.final_url}</a><div className="tags_qrac_stats"><strong>{Number(item.total_clicks || 0)}</strong><span>escaneos</span><small>Último: {item.last_click_at ? new Date(item.last_click_at).toLocaleString("es-AR") : "sin actividad"}</small></div><footer><button onClick={() => edit(item)}><FaPen /> Editar</button><a href={`/api/qr/download/${item.code}?format=png`}><FaDownload /> Descargar</a></footer></article>)}</section>}
        {statsEnabled && <section className="tags_qrac_analytics"><header><div><FaChartLine /><div><h2>Mis estadísticas</h2><p>Consultá el rendimiento de tus códigos QR.</p></div></div><div className="tags_qrac_analytics_filters"><label>QR<select value={qrId} onChange={event => setQrId(event.target.value)}><option value="all">Todos mis QRs</option>{data.qrs.map(item => <option key={item.qr_id} value={item.qr_id}>{item.code} · {item.label}</option>)}</select></label><label>Período<select value={days} onChange={event => setDays(event.target.value)}><option value="7">Últimos 7 días</option><option value="30">Últimos 30 días</option><option value="90">Últimos 90 días</option><option value="365">Últimos 365 días</option></select></label></div></header><div className="tags_qrac_analytics_kpis"><article><span>Clicks</span><strong>{Number(stats.summary?.totalClicks || 0)}</strong></article><article><span>Usuarios únicos</span><strong>{Number(stats.summary?.uniqueClicks || 0)}</strong></article></div><div className="tags_qrac_analytics_charts"><div><TimelineChart data={stats.timeline || []} /></div><div><QrsClicks data={stats.qrStats || []} /></div></div><div className="tags_qrac_analytics_tables"><div><h3>Dispositivos</h3><table><tbody>{(stats.devices || []).map(item => <tr key={item.device_type}><td>{item.device_type || "No identificado"}</td><td>{item.total}</td></tr>)}</tbody></table></div><div><h3>Provincia / ciudad</h3><table><tbody>{(stats.geo?.cities || []).map(item => <tr key={`${item.region || ""}-${item.city}`}><td>{[item.region, item.city].filter(Boolean).join(" / ") || "No identificada"}</td><td>{item.total}</td></tr>)}</tbody></table></div></div></section>}
        {form && <div className="tags_qrac_overlay"><form onSubmit={save}><header><h2>Editar código QR</h2><button type="button" onClick={() => setForm(null)}><FaXmark /></button></header><label>Nombre<input required value={form.label} onChange={event => setForm({ ...form, label: event.target.value })} /></label><label>Destino<input required type="url" value={form.finalUrl} onChange={event => setForm({ ...form, finalUrl: event.target.value })} /></label><label className="tags_qrac_checkbox"><input type="checkbox" checked={Boolean(form.browserGeolocationEnabled)} onChange={event => setForm({ ...form, browserGeolocationEnabled: event.target.checked })} /> Pedir ubicación del navegador al escanear<div>Solicita permiso y guarda provincia y ciudad cuando el dispositivo lo permite.</div></label><label>Estado<select value={form.status} onChange={event => setForm({ ...form, status: event.target.value })}><option value="active">Activo</option><option value="paused">Pausado</option></select></label>{form.status === "paused" && <label>Mensaje de pausa<textarea required value={form.stopMessage} onChange={event => setForm({ ...form, stopMessage: event.target.value })} /></label>}<footer><button type="button" onClick={() => setForm(null)}>Cancelar</button><button type="submit">Guardar</button></footer></form></div>}
    </main>;
}
