CREATE TABLE IF NOT EXISTS tags_benefit_merchants (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,business_id BIGINT UNSIGNED NULL,created_by_business_id BIGINT UNSIGNED NULL,name VARCHAR(190) NOT NULL,tax_id VARCHAR(40) NULL,email VARCHAR(190) NULL,phone VARCHAR(60) NULL,status VARCHAR(30) NOT NULL DEFAULT 'active',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_tags_benefit_merchant_business(business_id),KEY idx_tags_benefit_merchants_creator(created_by_business_id,status),KEY idx_tags_benefit_merchants_status(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS tags_benefit_locations (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,merchant_id BIGINT UNSIGNED NOT NULL,name VARCHAR(190) NOT NULL,address VARCHAR(500) NULL,latitude DECIMAL(10,7) NULL,longitude DECIMAL(10,7) NULL,phone VARCHAR(60) NULL,whatsapp VARCHAR(60) NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_tags_benefit_locations_merchant(merchant_id,is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS tags_benefit_staff (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,merchant_id BIGINT UNSIGNED NOT NULL,location_id BIGINT UNSIGNED NULL,name VARCHAR(190) NOT NULL,email VARCHAR(190) NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'active',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_tags_benefit_staff_email(merchant_id,email),KEY idx_tags_benefit_staff_location(location_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS tags_benefit_staff_tokens (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,staff_id BIGINT UNSIGNED NOT NULL,token_hash CHAR(64) NOT NULL,expires_at DATETIME NOT NULL,used_at DATETIME NULL,requested_ip VARCHAR(64) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_tags_benefit_staff_token(token_hash),KEY idx_tags_benefit_staff_tokens_staff(staff_id,expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS tags_benefit_staff_sessions (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,staff_id BIGINT UNSIGNED NOT NULL,merchant_id BIGINT UNSIGNED NOT NULL,session_hash CHAR(64) NOT NULL,expires_at DATETIME NOT NULL,last_seen_at DATETIME NULL,revoked_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_tags_benefit_staff_session(session_hash),KEY idx_tags_benefit_staff_sessions_staff(staff_id,expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS tags_benefit_categories (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,issuer_business_id BIGINT UNSIGNED NULL,guest_app_id BIGINT UNSIGNED NULL,name VARCHAR(120) NOT NULL,icon_code VARCHAR(60) NULL,sort_order INT NOT NULL DEFAULT 0,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_tags_benefit_categories_scope(guest_app_id,is_active,sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS tags_benefit_campaigns (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,merchant_id BIGINT UNSIGNED NOT NULL,location_id BIGINT UNSIGNED NULL,category_id BIGINT UNSIGNED NULL,issuer_type VARCHAR(30) NOT NULL,issuer_business_id BIGINT UNSIGNED NULL,guest_app_id BIGINT UNSIGNED NULL,name VARCHAR(190) NOT NULL,image_url VARCHAR(2000) NULL,description VARCHAR(1000) NULL,conditions_text TEXT NULL,usage_instructions VARCHAR(1000) NULL,benefit_type VARCHAR(40) NOT NULL DEFAULT 'custom',benefit_value DECIMAL(12,2) NULL,valid_from DATETIME NULL,valid_until DATETIME NULL,limit_scope VARCHAR(30) NOT NULL DEFAULT 'stay',max_issues INT NOT NULL DEFAULT 1,scope_type VARCHAR(30) NOT NULL DEFAULT 'guest_app',status VARCHAR(30) NOT NULL DEFAULT 'draft',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_tags_benefit_campaigns_scope(scope_type,guest_app_id,status),KEY idx_tags_benefit_campaigns_merchant(merchant_id,status),KEY idx_tags_benefit_campaigns_category(category_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS tags_benefit_campaign_scopes (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,campaign_id BIGINT UNSIGNED NOT NULL,scope_type VARCHAR(30) NOT NULL,scope_id BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_tags_benefit_campaign_scope(campaign_id,scope_type,scope_id),KEY idx_tags_benefit_campaign_scopes_lookup(scope_type,scope_id,campaign_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS tags_benefit_coupons (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,campaign_id BIGINT UNSIGNED NOT NULL,code VARCHAR(40) NOT NULL,signature_hash CHAR(64) NOT NULL,user_id BIGINT UNSIGNED NULL,guest_app_id BIGINT UNSIGNED NULL,stay_id BIGINT UNSIGNED NULL,guest_id BIGINT UNSIGNED NULL,status VARCHAR(30) NOT NULL DEFAULT 'issued',issued_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,expires_at DATETIME NULL,redeemed_at DATETIME NULL,cancelled_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_tags_benefit_coupon_code(code),KEY idx_tags_benefit_coupon_owner(stay_id,guest_id,status),KEY idx_tags_benefit_coupon_campaign(campaign_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS tags_benefit_redemptions (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,coupon_id BIGINT UNSIGNED NOT NULL,merchant_id BIGINT UNSIGNED NOT NULL,location_id BIGINT UNSIGNED NULL,staff_id BIGINT UNSIGNED NULL,status VARCHAR(30) NOT NULL DEFAULT 'confirmed',redeemed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,ip_address VARCHAR(64) NULL,user_agent VARCHAR(500) NULL,notes VARCHAR(1000) NULL,reversed_at DATETIME NULL,reversal_reason VARCHAR(1000) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_tags_benefit_redemptions_coupon(coupon_id,redeemed_at),KEY idx_tags_benefit_redemptions_merchant(merchant_id,redeemed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS tags_benefit_audit_log (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,merchant_id BIGINT UNSIGNED NULL,campaign_id BIGINT UNSIGNED NULL,coupon_id BIGINT UNSIGNED NULL,actor_type VARCHAR(30) NOT NULL,actor_id BIGINT UNSIGNED NULL,action VARCHAR(100) NOT NULL,metadata_json JSON NULL,ip_address VARCHAR(64) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_tags_benefit_audit_merchant(merchant_id,created_at),KEY idx_tags_benefit_audit_coupon(coupon_id,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
