"use client";

import { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { FaCalendarCheck, FaChevronDown, FaClock, FaPen, FaPlus, FaTrash } from "react-icons/fa6";
import { getTurnosTemplate, TURNOS_TEMPLATE_OPTIONS } from "@/app/modules/turnos/lib/turnosTemplates";
import TurnosAdminAgenda from "@/app/modules/turnos/components/admin/TurnosAdminAgenda";
import TurnosAdminBlocks from "@/app/modules/turnos/components/admin/TurnosAdminBlocks";
import TurnosAdminPolicies from "@/app/modules/turnos/components/admin/TurnosAdminPolicies";
import TurnosAdminPublication from "@/app/modules/turnos/components/admin/TurnosAdminPublication";
import TurnosConfigurationGuide from "@/app/modules/turnos/components/admin/TurnosConfigurationGuide";
import TurnosAdminTabs from "@/app/modules/turnos/components/admin/TurnosAdminTabs";
import TurnosAdminCalendar from "@/app/modules/turnos/components/admin/TurnosAdminCalendar";
import TurnosAdminCustomers from "@/app/modules/turnos/components/admin/TurnosAdminCustomers";
import showAlert from "@/app/components/showAlert";
import TagsSpinner from "@/app/components/TagsSpinner";
import AiChatSurfaceSettings from "@/app/modules/ai-chat/components/admin/AiChatSurfaceSettings";
import "@/app/modules/turnos/styles/turnos-admin.css";
import "@/app/styles/tags_dashboard.css";

const DAYS = ["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"];

export default function TurnosAdminPageClient({ businessId }) {
    const router = useRouter();
    const params = useSearchParams();
    const [apps, setApps] = useState([]), [app, setApp] = useState(null), [services, setServices] = useState([]), [resources, setResources] = useState([]), [resourceTypes, setResourceTypes] = useState([]), [schedules, setSchedules] = useState([]);
    const [settings, setSettings] = useState({}), [publicPolicy, setPublicPolicy] = useState({}), [depositPolicy, setDepositPolicy] = useState({}), [message, setMessage] = useState(""), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false);
    const [templateCode, setTemplateCode] = useState("generic"), [editingServiceId, setEditingServiceId] = useState(null), [editingResourceId, setEditingResourceId] = useState(null), [editingScheduleId, setEditingScheduleId] = useState(null);
    const [serviceForm, setServiceForm] = useState({ name: "", resourceTypeId: "", durationMinutes: 30, bookingChannelMode: "hybrid", confirmationMode: "automatic", customerIdentificationMode: "contact", cancellationNoticeMinutes: 0, rescheduleNoticeMinutes: 0 });
    const [resourceForm, setResourceForm] = useState({ name: "", serviceId: "", resourceTypeId: "", capacity: 1, allowConsecutiveBookings: false, maxConsecutiveSlots: 2 });
    const [scheduleForm, setScheduleForm] = useState({ scopeType: "app", scopeId: "", weekday: 1, startTime: "09:00", endTime: "18:00", slotIntervalMinutes: 30 });
    const [activeTab, setActiveTab] = useState("agenda");
    const [calendarRange, setCalendarRange] = useState(null);

    const selectedId = Number(app?.id || params.get("turnosId") || 0);
    const selectedTemplate = getTurnosTemplate(templateCode);

    async function load(targetId = selectedId, { silent = false } = {}) {
        if (!silent) setLoading(true);
        const query = new URLSearchParams({ businessId: String(businessId) });
        if (targetId) query.set("turnosId", String(targetId));
        try {
            const responses = await Promise.all(["settings", "services", "resources", "resource-types", "schedules"].map(name => fetch(`/api/turnos/admin/${name}?${query}`)));
            const payloads = await Promise.all(responses.map(response => response.json()));
            const settingsPayload = payloads[0];
            setApps(settingsPayload.apps || []);
            if (!settingsPayload.ok) { setApp(null); setMessage(settingsPayload.error || "No hay una instancia de Turnos seleccionada."); return; }
            const nextApp = settingsPayload.settings;
            setApp(nextApp); setSettings(nextApp.settings || {}); setPublicPolicy(nextApp.publicBookingPolicy || {}); setDepositPolicy(nextApp.depositPolicy || {}); setTemplateCode((nextApp.settings || {}).turnosTemplate || nextApp.business_profile_code || "generic");
            setServices(payloads[1].services || []); setResources(payloads[2].resources || []); setResourceTypes(payloads[3].resourceTypes || []); setSchedules(payloads[4].schedules || []); setMessage("");
        } catch { setMessage("No se pudo cargar la instancia de Turnos."); } finally { if (!silent) setLoading(false); }
    }

    useEffect(() => { load(Number(params.get("turnosId") || 0)); }, [businessId, params]);
    useEffect(() => {
        if (!editingServiceId) return;
        const item = services.find(service => Number(service.id) === Number(editingServiceId));
        if (item) setServiceForm(prev => ({ ...prev, resourceTypeId: item.required_resource_type_id || "", customerIdentificationMode: item.customer_identification_mode || "contact", confirmationMode: item.confirmation_mode || "automatic", cancellationNoticeMinutes: item.cancellation_notice_minutes || 0, rescheduleNoticeMinutes: item.reschedule_notice_minutes || 0 }));
    }, [editingServiceId]);
    useEffect(() => {
        if (!editingResourceId) return;
        const item = resources.find(resource => Number(resource.id) === Number(editingResourceId));
        if (item) { const metadata = typeof item.public_metadata_json === "string" ? JSON.parse(item.public_metadata_json || "{}") : item.public_metadata_json || {}; setResourceForm(prev => ({ ...prev, serviceId: item.service_id || "", capacity: item.capacity || 1, allowConsecutiveBookings: metadata.allowConsecutiveBookings === true, maxConsecutiveSlots: Number(metadata.maxConsecutiveSlots || 2) })); }
    }, [editingResourceId]);
    useEffect(() => {
        if (!editingScheduleId) return;
        const item = schedules.find(schedule => Number(schedule.id) === Number(editingScheduleId));
        if (item) setScheduleForm(prev => ({ ...prev, scopeType: item.scope_type || "app", scopeId: item.scope_type === "resource" ? item.scope_id : "" }));
    }, [editingScheduleId]);

    async function save(endpoint, method, body, success) {
        setSaving(true);
        try {
            const response = await fetch(endpoint, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify({ businessId, turnosId: selectedId, ...body }) });
            const payload = await response.json().catch(() => ({}));
            if (!response.ok) { await showAlert({ title: "No se pudo completar", text: payload.error || "No se pudo guardar la información.", icon: "error" }); return false; }
            await load(selectedId, { silent: true });
            await showAlert({ title: "Listo", text: success, icon: "success", timer: 1700 });
            return true;
        } catch { await showAlert({ title: "Error", text: "No se pudo comunicar con el servidor.", icon: "error" }); return false; }
        finally { setSaving(false); }
    }

    async function saveSettings(event) { event.preventDefault(); await save("/api/turnos/admin/settings", "POST", { settings: { ...settings, turnosTemplate: templateCode }, publicBookingPolicy: publicPolicy, depositPolicy }, "Configuración guardada."); }
    async function togglePublication() { await save("/api/turnos/admin/settings", "PATCH", { status: app?.status === "published" ? "draft" : "published" }, app?.status === "published" ? "Página despublicada." : "Página publicada."); }
    async function saveService(event) { event.preventDefault(); const ok = await save("/api/turnos/admin/services", editingServiceId ? "PUT" : "POST", { ...serviceForm, serviceId: editingServiceId, bookingMode: selectedTemplate.bookingMode }, editingServiceId ? "Servicio actualizado." : "Servicio creado."); if (ok) { setEditingServiceId(null); setServiceForm({ ...serviceForm, name: "" }); } }
    async function saveResource(event) { event.preventDefault(); const ok = await save("/api/turnos/admin/resources", editingResourceId ? "PUT" : "POST", { ...resourceForm, resourceId: editingResourceId }, editingResourceId ? "Recurso actualizado." : "Recurso creado."); if (ok) { setEditingResourceId(null); setResourceForm({ ...resourceForm, name: "" }); } }
    async function saveSchedule(event) { event.preventDefault(); const existingId = editingScheduleId && schedules.some(item => Number(item.id) === Number(editingScheduleId)) ? editingScheduleId : null; if (editingScheduleId && !existingId) setEditingScheduleId(null); const ok = await save("/api/turnos/admin/schedules", existingId ? "PUT" : "POST", { ...scheduleForm, scheduleId: existingId }, existingId ? "Horario actualizado." : "Horario agregado."); if (ok) setEditingScheduleId(null); }
    async function remove(endpoint, id, label) { const confirmed = await showAlert({ title: "Confirmar eliminación", text: "Esta acción quitará el elemento de la configuración.", icon: "warning", showCancelButton: true, confirmButtonText: "Eliminar" }); if (!confirmed) return; await save(endpoint, "DELETE", { [`${label}Id`]: id }, `${label[0].toUpperCase()}${label.slice(1)} eliminado.`); }

    if (loading) return <TagsSpinner size={120} logoSize={66} borderSize={5} background="rgba(255,255,255,.72)" />;
    if (!app) return <main className="tags_dashboard_page"><section className="tags_portal_section"><div className="tags_portal_section_header"><div><h2>Tags Turnos</h2><p>Seleccioná una instancia desde el dashboard del negocio.</p></div><button className="tags_btn rounded" type="button" onClick={() => router.push(`/dashboard/businesses/${businessId}`)}>Volver al dashboard</button></div><div className="tags_portal_empty">{message || "No hay una instancia disponible."}</div></section></main>;

    return <main className="tags_dashboard_page tags_turnos_admin_workspace" data-active-tab={activeTab}>
        <header className="tags_dashboard_hero turnos_admin_platform_header"><div className="tags_dashboard_hero_left"><div className="tags_dashboard_logo_box"><FaCalendarCheck /></div><div><span className="tags_portal_dashboard_label">MÓDULO DEL NEGOCIO</span><h1 className="tags_dashboard_title">{app.name}</h1><p className="tags_dashboard_subtitle">Tags Turnos · {selectedTemplate.label}</p></div></div><div className="tags_dashboard_hero_actions"><button className="tags_dashboard_back_btn" type="button" onClick={() => router.push(`/dashboard/businesses/${businessId}`)}>Volver al negocio</button><button className="tags_dashboard_back_btn turnos_admin_publish_button" type="button" onClick={togglePublication}>{app.status === "published" ? "Despublicar" : "Publicar"}</button></div></header>
        {message && <div className="tags_portal_empty turnos_admin_notice">{message}</div>}
        <section className="tags_portal_section turnos_admin_instance_section"><div className="tags_portal_section_header"><div><h2>Instancias de Turnos</h2><p>Cada instancia tiene su propia página, slug, servicios, recursos y reservas.</p></div><button className="tags_btn rounded" type="button" onClick={() => router.push(`/dashboard/businesses/${businessId}`)}><FaPlus /> Crear otra instancia</button></div><div className="turnos_admin_instance_selector"><FaCalendarCheck /><select value={app.id} onChange={event => router.push(`/dashboard/businesses/${businessId}/turnos?turnosId=${event.target.value}`)}>{apps.map(item => <option key={item.id} value={item.id}>{item.name} · /p/{item.slug} · {item.status === "published" ? "Publicada" : "No publicada"}</option>)}</select><FaChevronDown /></div></section>
        <section className="tags_portal_section"><div className="tags_portal_section_header"><div><h2>Configuración de la instancia</h2><p>Definí la plantilla inicial y conservá la identidad visual del negocio.</p></div></div><form onSubmit={saveSettings} className="turnos_admin_platform_grid"><div className="tags_portal_summary_card"><label>Tipo de negocio<select value={templateCode} onChange={event => setTemplateCode(event.target.value)}>{TURNOS_TEMPLATE_OPTIONS.map(item => <option key={item.code} value={item.code}>{item.label}</option>)}</select></label><p>{selectedTemplate.description}</p><button className="tags_btn rounded" disabled={saving} type="submit">Guardar configuración</button></div><div className="tags_portal_summary_card"><span>Estado público</span><strong>{app.status === "published" ? "Publicado" : "No publicado"}</strong><span className="turnos_admin_public_url">/p/{app.slug}</span><small>La activación y el slug se administran desde el dashboard del negocio.</small></div></form></section>
        <section className="tags_portal_section"><div className="tags_portal_section_header"><div><h2>Servicios, recursos y horarios</h2><p>El servicio define duración y tipo de recurso; cada recurso define capacidad y puede tener horarios propios.</p></div></div><div className="turnos_admin_platform_forms" data-editing={editingServiceId ? "service" : editingResourceId ? "resource" : editingScheduleId ? "schedule" : "none"}>
            <form className="tags_portal_summary_card" onSubmit={saveService}><h3>{editingServiceId ? "Editar servicio" : `Nuevo ${selectedTemplate.serviceLabel.toLowerCase()}`}</h3><label>Nombre del servicio<input required value={serviceForm.name} onChange={event => setServiceForm({ ...serviceForm, name: event.target.value })} /></label><label>Personal, espacio o equipo necesario<select required value={serviceForm.resourceTypeId} onChange={event => setServiceForm({ ...serviceForm, resourceTypeId: event.target.value })}><option value="">Seleccionar qué necesita este servicio</option>{resourceTypes.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Duración (minutos)<input type="number" min="1" value={serviceForm.durationMinutes} onChange={event => setServiceForm({ ...serviceForm, durationMinutes: event.target.value })} /></label><label>Quién puede crear reservas<select value={serviceForm.bookingChannelMode} onChange={event => setServiceForm({ ...serviceForm, bookingChannelMode: event.target.value })}><option value="admin_only">Sólo el negocio</option><option value="public_request">El cliente solicita; el negocio confirma</option><option value="public_auto_confirm">El cliente reserva y se confirma</option><option value="hybrid">Público y administración</option></select></label><label>Identificación del cliente<select value={serviceForm.customerIdentificationMode} onChange={event => setServiceForm({ ...serviceForm, customerIdentificationMode: event.target.value })}><option value="contact">Nombre y contacto</option><option value="magic_link">Verificación por email</option></select></label><label>Confirmación<select value={serviceForm.confirmationMode} onChange={event => setServiceForm({ ...serviceForm, confirmationMode: event.target.value })}><option value="automatic">Automática</option><option value="manual">Manual por el negocio</option></select></label><label>Minutos antes para cancelar<input type="number" min="0" value={serviceForm.cancellationNoticeMinutes} onChange={event => setServiceForm({ ...serviceForm, cancellationNoticeMinutes: event.target.value })} /></label><label>Minutos antes para reprogramar<input type="number" min="0" value={serviceForm.rescheduleNoticeMinutes} onChange={event => setServiceForm({ ...serviceForm, rescheduleNoticeMinutes: event.target.value })} /></label><button className="tags_btn rounded" type="submit">{editingServiceId ? "Guardar cambios" : "Crear servicio"}</button></form>
            <form className="tags_portal_summary_card" onSubmit={saveResource}><h3>{editingResourceId ? "Editar recurso" : `Nuevo ${selectedTemplate.resourceLabel.toLowerCase()}`}</h3><label>Servicio al que pertenece<select required value={resourceForm.serviceId} onChange={event => { const service = services.find(item => String(item.id) === event.target.value); setResourceForm({ ...resourceForm, serviceId: event.target.value, resourceTypeId: service?.required_resource_type_id || "" }); }}><option value="">Seleccionar servicio</option>{services.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Nombre identificable<input required placeholder={templateCode === "bike_kayak" ? "Ej.: Bicicletas rodado 26" : "Nombre"} value={resourceForm.name} onChange={event => setResourceForm({ ...resourceForm, name: event.target.value })} /></label><label>Clase de personal, espacio o equipo<select required value={resourceForm.resourceTypeId} onChange={event => setResourceForm({ ...resourceForm, resourceTypeId: event.target.value })}><option value="">Seleccionar clase</option>{resourceTypes.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Capacidad simultánea<input type="number" min="1" value={resourceForm.capacity} onChange={event => setResourceForm({ ...resourceForm, capacity: event.target.value })} /></label><small>{templateCode === "bike_kayak" ? "Ejemplo: 10 significa que se pueden alquilar diez unidades al mismo tiempo." : "Cantidad de reservas que este recurso puede atender al mismo tiempo."}</small><label className="tags_turnos_admin_consecutive_toggle"><input type="checkbox" checked={resourceForm.allowConsecutiveBookings} onChange={event => setResourceForm({ ...resourceForm, allowConsecutiveBookings: event.target.checked })} />Permitir reservar varios turnos consecutivos</label>{resourceForm.allowConsecutiveBookings && <label>Máximo de turnos consecutivos<input type="number" min="2" max="96" value={resourceForm.maxConsecutiveSlots} onChange={event => setResourceForm({ ...resourceForm, maxConsecutiveSlots: event.target.value })} /></label>}<button className="tags_btn rounded" type="submit">{editingResourceId ? "Guardar cambios" : "Crear recurso"}</button></form>
            <form className="tags_portal_summary_card" onSubmit={saveSchedule}><h3>{editingScheduleId ? "Editar horario" : "Horario semanal"}</h3><select value={scheduleForm.scopeType} onChange={event => setScheduleForm({ ...scheduleForm, scopeType: event.target.value, scopeId: "" })}><option value="app">Horario general</option><option value="resource">Horario de un recurso</option></select>{scheduleForm.scopeType === "resource" && <select required value={scheduleForm.scopeId} onChange={event => setScheduleForm({ ...scheduleForm, scopeId: event.target.value })}><option value="">Seleccionar recurso</option>{resources.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select>}<select value={scheduleForm.weekday} onChange={event => setScheduleForm({ ...scheduleForm, weekday: event.target.value })}>{DAYS.map((day, index) => <option key={day} value={index}>{day}</option>)}</select><input type="time" value={scheduleForm.startTime} onChange={event => setScheduleForm({ ...scheduleForm, startTime: event.target.value })} /><input type="time" value={scheduleForm.endTime} onChange={event => setScheduleForm({ ...scheduleForm, endTime: event.target.value })} /><input type="number" min="5" value={scheduleForm.slotIntervalMinutes} onChange={event => setScheduleForm({ ...scheduleForm, slotIntervalMinutes: event.target.value })} /><button className="tags_btn rounded" type="submit">{editingScheduleId ? "Guardar cambios" : "Agregar horario"}</button></form>
        </div>{(editingServiceId || editingResourceId || editingScheduleId) && <button className="tags_turnos_admin_modal_cancel" type="button" title="Cerrar" aria-label="Cerrar edición" onClick={() => { setEditingServiceId(null); setEditingResourceId(null); setEditingScheduleId(null); }}>×</button>}</section>
        <section className="tags_portal_section"><div className="turnos_admin_platform_lists"><div className="tags_table_wrapper"><h3>Servicios</h3><table className="tags_table"><tbody>{services.map(item => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.duration_minutes} minutos</small></td><td><button className="tags_dashboard_icon_btn" title="Editar" type="button" onClick={() => { setEditingServiceId(item.id); setServiceForm({ name: item.name, durationMinutes: item.duration_minutes, bookingChannelMode: item.booking_channel_mode, confirmationMode: item.confirmation_mode }); }}><FaPen /></button><button className="tags_dashboard_icon_btn danger" title="Eliminar" type="button" onClick={() => remove("/api/turnos/admin/services", item.id, "service")}><FaTrash /></button></td></tr>)}</tbody></table></div><div className="tags_table_wrapper"><h3>Recursos</h3><table className="tags_table"><tbody>{resources.map(item => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.resource_type_name}</small></td><td><button className="tags_dashboard_icon_btn" title="Editar" type="button" onClick={() => { setEditingResourceId(item.id); setResourceForm({ name: item.name, resourceTypeId: item.resource_type_id }); }}><FaPen /></button><button className="tags_dashboard_icon_btn danger" title="Eliminar" type="button" onClick={() => remove("/api/turnos/admin/resources", item.id, "resource")}><FaTrash /></button></td></tr>)}</tbody></table></div><div className="tags_table_wrapper"><h3>Horarios</h3><table className="tags_table"><tbody>{schedules.map(item => <tr key={item.id}><td><strong>{DAYS[item.weekday]}</strong><small>{String(item.start_time).slice(0, 5)}–{String(item.end_time).slice(0, 5)} · cada {item.slot_interval_minutes} min</small></td><td><button className="tags_dashboard_icon_btn" title="Editar" type="button" onClick={() => { setEditingScheduleId(item.id); setScheduleForm({ weekday: item.weekday, startTime: String(item.start_time).slice(0, 5), endTime: String(item.end_time).slice(0, 5), slotIntervalMinutes: item.slot_interval_minutes }); }}><FaPen /></button><button className="tags_dashboard_icon_btn danger" title="Eliminar" type="button" onClick={() => remove("/api/turnos/admin/schedules", item.id, "schedule")}><FaTrash /></button></td></tr>)}</tbody></table></div></div></section>
        <TurnosConfigurationGuide templateCode={templateCode} />
        <TurnosAdminAgenda businessId={businessId} turnosId={selectedId} services={services} resources={resources} initialRange={calendarRange} />
        <TurnosAdminCustomers businessId={businessId} turnosId={selectedId} />
        <TurnosAdminPublication businessId={businessId} turnosId={selectedId} slug={app.slug} name={app.name} status={app.status} onSaved={() => load(selectedId, { silent: true })} />
        <TurnosAdminPolicies businessId={businessId} turnosId={selectedId} settings={settings} publicPolicy={publicPolicy} depositPolicy={depositPolicy} onSaved={() => load(selectedId, { silent: true })} />
        <AiChatSurfaceSettings businessId={businessId} surfaceType="turnos" surfaceId={selectedId} surfaceLabel="la página pública de Turnos" />
        <TurnosAdminBlocks businessId={businessId} turnosId={selectedId} resources={resources} />
        <TurnosAdminTabs value={activeTab} onChange={setActiveTab} />
        <TurnosAdminCalendar businessId={businessId} turnosId={selectedId} onCreateRange={range => { setCalendarRange(range); setActiveTab("reservations"); }} />
        {saving && <TagsSpinner size={120} logoSize={66} borderSize={5} background="rgba(255,255,255,.72)" />}
    </main>;
}
