"use client";
import { useState } from "react";
import { FaArrowDown, FaArrowUp, FaEye, FaEyeSlash, FaImages, FaLayerGroup, FaPen, FaPlus, FaStore, FaTrash, FaUser, FaAddressBook, FaTag } from "react-icons/fa6";
import TagsSpinner from "@/app/components/TagsSpinner";
import showAlert from "@/app/components/showAlert";
import DirectorySectionEditor from "./DirectorySectionEditor";
import "./DirectoryStructureManager.css";

async function responsePayload(response) { const text = await response.text(); try { return text ? JSON.parse(text) : {}; } catch { return {}; } }
function kindOf(section) { const type = section?.blocks?.[0]?.type; return section?.settings_json?.directoryBaseSlot || (type === "gallery" ? "gallery" : type === "contact_info" ? "contact" : type === "catalog" || section.type === "catalog" ? "catalog" : type === "benefits" ? "benefits" : "web"); }
const META = { presentation: [FaUser, "Presentacion", "Titulo, textos y parrafos."], gallery: [FaImages, "Galeria", "Imagenes de la ficha."], catalog: [FaStore, "Catalogo", "Productos y categorias."], contact: [FaAddressBook, "Contacto", "Datos y acciones de contacto."], benefits: [FaTag, "Beneficios", "Promociones privadas y publicas."], web: [FaLayerGroup, "Seccion web", "Contenido libre de la ficha."] };

export default function DirectoryStructureManager({ businessId, pageId, sections = [], onReload }) {
  const [busy, setBusy] = useState(false), [editing, setEditing] = useState(null);
  const ordered = [...sections].sort((a, b) => Number(a.sort_order) - Number(b.sort_order));
  async function post(url, body) { const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ businessId, pageId, ...body }) }); const result = await responsePayload(response); if (!response.ok) throw new Error(result.error || "No se pudo completar la operacion"); return result; }
  async function run(action, success) { setBusy(true); try { await action(); await onReload(); if (success) await showAlert({ title: success, icon: "success", timer: 1100 }); } catch (error) { await showAlert({ title: "No se pudo completar", text: error.message, icon: "error" }); } finally { setBusy(false); } }
  function move(index, direction) { const target = index + direction; if (target < 0 || target >= ordered.length) return; const next = [...ordered]; [next[index], next[target]] = [next[target], next[index]]; run(() => post("/api/qr-page/sections/reorder", { sections: next.map((section, position) => ({ id: section.id, sort_order: position + 1 })) })); }
  function add() { run(async () => { const created = await post("/api/qr-page/sections/create", { type: "content", title: "Nueva seccion", settings_json: { directoryBaseSlot: "web" }, styles_json: {} }); await post("/api/qr-page/blocks/create", { sectionId: created.sectionId, type: "web_section", content_json: { eyebrow: "", title: "Nueva seccion", subtitle: "", highlightedText: "", paragraphs: ["Escribi aqui el contenido de esta seccion."], images: [], imageLayout: "grid" }, styles_json: { alignment: "left" } }); }, "Seccion creada"); }
  function addBenefits() { if (ordered.some(section => kindOf(section) === "benefits")) return showAlert({ title: "Beneficios ya existe", text: "Edita la seccion existente en la lista.", icon: "info" }); run(async () => { const created = await post("/api/qr-page/sections/create", { type: "content", title: "Beneficios", settings_json: { directoryBaseSlot: "benefits" }, styles_json: {} }); await post("/api/qr-page/blocks/create", { sectionId: created.sectionId, type: "benefits", content_json: { eyebrow: "BENEFICIOS", title: "Beneficios para vos", subtitle: "Promociones vigentes de este negocio" }, styles_json: { alignment: "left" } }); }, "Seccion de beneficios creada"); }
  function toggle(section) { run(() => post("/api/qr-page/sections/update", { sectionId: section.id, type: section.type, title: section.title, is_visible: Number(section.is_visible) ? 0 : 1, settings_json: section.settings_json || {}, styles_json: section.styles_json || {} })); }
  async function remove(section) { if (!["web", "benefits"].includes(kindOf(section))) return; const confirmed = await showAlert({ title: "Eliminar esta seccion?", text: "Se eliminaran sus textos e imagenes.", icon: "warning", showCancelButton: true, confirmButtonText: "Eliminar", cancelButtonText: "Cancelar" }); if (confirmed) run(() => post("/api/qr-page/sections/delete", { sectionId: section.id }), "Seccion eliminada"); }
  return <div className="tags_directory_structure">{busy && <div className="tags_directory_structure_busy"><TagsSpinner /></div>}<header><div><h2>Estructura de la Web</h2><p>Ordena, edita, muestra u oculta cada bloque. Los cambios se reflejan en la misma ficha publica.</p></div><div><button type="button" onClick={add}><FaPlus /> Agregar seccion</button><button type="button" onClick={addBenefits}><FaTag /> Agregar beneficios</button></div></header><div className="tags_directory_structure_list">{ordered.map((section, index) => { const kind = kindOf(section), [Icon, label, description] = META[kind] || META.web; return <article className={Number(section.is_visible) ? "" : "is_hidden"} key={section.id}><div className="tags_directory_structure_identity"><span><Icon /></span><div><small>{label}</small><h3>{section.title || label}</h3><p>{description}</p></div></div><div className="tags_directory_structure_actions"><button type="button" onClick={() => move(index, -1)} disabled={index === 0}><FaArrowUp /><span>Subir</span></button><button type="button" onClick={() => move(index, 1)} disabled={index === ordered.length - 1}><FaArrowDown /><span>Bajar</span></button><button type="button" onClick={() => setEditing(section)}><FaPen /><span>Editar</span></button><button type="button" onClick={() => toggle(section)}>{Number(section.is_visible) ? <FaEye /> : <FaEyeSlash />}<span>{Number(section.is_visible) ? "Visible" : "Oculto"}</span></button>{["web", "benefits"].includes(kind) && <button type="button" className="danger" onClick={() => remove(section)}><FaTrash /><span>Eliminar</span></button>}</div></article>; })}</div>{editing && <DirectorySectionEditor businessId={businessId} pageId={pageId} section={editing} onClose={() => setEditing(null)} onSaved={onReload} />}</div>;
}
