"use client";

import { useEffect, useState } from "react";
import { FaPen, FaPlus, FaTrash, FaTag } from "react-icons/fa6";
import MediaUploader from "@/app/components/MediaUploader";
import TagsSpinner from "@/app/components/TagsSpinner";
import showAlert from "@/app/components/showAlert";
import { directoryBenefitLabel } from "../../lib/directoryBenefitFormatting";
import "./DirectoryBenefitsManager.css";

const EMPTY = { id: 0, name: "", benefitType: "amount", benefitValue: "", promotionBuyQuantity: "", promotionPayQuantity: "", promotionItem: "", validFrom: "", validUntil: "", description: "", imageUrl: "", visibility: "private", isActive: true, sortOrder: 0 };
async function payload(response) { const text = await response.text(); try { return text ? JSON.parse(text) : {}; } catch { return {}; } }

export default function DirectoryBenefitsManager({ businessId, pageId, onReload }) {
  const [benefits, setBenefits] = useState([]), [form, setForm] = useState(EMPTY), [editing, setEditing] = useState(false), [busy, setBusy] = useState(true);
  async function load() { setBusy(true); try { const response = await fetch(`/api/directory/client/benefits?businessId=${businessId}&pageId=${pageId}`, { cache: "no-store" }); const result = await payload(response); if (!response.ok) throw new Error(result.error || "No se pudieron cargar los beneficios."); setBenefits(result.benefits || []); } catch (error) { await showAlert({ title: "No se pudieron cargar", text: error.message, icon: "error" }); } finally { setBusy(false); } }
  useEffect(() => { load(); }, [businessId, pageId]);
  function edit(item) { setForm({ ...EMPTY, id: item.id, name: item.name || "", benefitType: item.benefit_type || "amount", benefitValue: item.benefit_value ?? "", promotionBuyQuantity: item.promotion_buy_quantity ?? "", promotionPayQuantity: item.promotion_pay_quantity ?? "", promotionItem: item.promotion_item || "", validFrom: String(item.valid_from || "").slice(0, 10), validUntil: String(item.valid_until || "").slice(0, 10), description: item.description || "", imageUrl: item.image_url || "", visibility: item.visibility || "private", isActive: Number(item.is_active) !== 0, sortOrder: item.sort_order || 0 }); setEditing(true); }
  function reset() { setForm(EMPTY); setEditing(false); }
  function update(field, value) { setForm(current => ({ ...current, [field]: value })); }
  async function save(event) { event.preventDefault(); if (!form.name.trim() || !form.validFrom || !form.validUntil) return showAlert({ title: "Faltan datos", text: "Completá nombre y fechas de validez.", icon: "warning" }); setBusy(true); try { const response = await fetch("/api/directory/client/benefits", { method: form.id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ businessId, pageId, ...form }) }); const result = await payload(response); if (!response.ok) throw new Error(result.error || "No se pudo guardar el beneficio."); reset(); await load(); await onReload(); await showAlert({ title: "Beneficio guardado", icon: "success", timer: 1200 }); } catch (error) { await showAlert({ title: "No se pudo guardar", text: error.message, icon: "error" }); } finally { setBusy(false); } }
  async function remove(item) { const confirmed = await showAlert({ title: "¿Eliminar beneficio?", text: "Se quitará de la ficha y no aparecerá en Beneficios públicos.", icon: "warning", showCancelButton: true, confirmButtonText: "Eliminar", cancelButtonText: "Cancelar" }); if (!confirmed) return; setBusy(true); try { const response = await fetch("/api/directory/client/benefits", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ businessId, pageId, id: item.id }) }); const result = await payload(response); if (!response.ok) throw new Error(result.error || "No se pudo eliminar."); await load(); await onReload(); } catch (error) { await showAlert({ title: "No se pudo eliminar", text: error.message, icon: "error" }); } finally { setBusy(false); } }
  return <div className="tags_directory_benefits_manager">
    {busy && <div className="tags_directory_benefits_busy"><TagsSpinner /></div>}
    <header><div><h2>Beneficios</h2><p>Creá promociones privadas para la Web o públicas para el Directorio.</p></div><button type="button" onClick={() => { reset(); setEditing(true); }}><FaPlus /> Nuevo beneficio</button></header>
    {!benefits.length && !editing && <div className="tags_directory_benefits_empty"><FaTag /><strong>Todavía no hay beneficios</strong><span>Podés publicar descuentos por monto, porcentaje o cantidad.</span></div>}
    <div className="tags_directory_benefits_list">{benefits.map(item => <article key={item.id} className={Number(item.is_active) ? "" : "is_inactive"}><div className="tags_directory_benefits_card_image">{item.image_url ? <img src={item.image_url} alt="" /> : <FaTag />}</div><div className="tags_directory_benefits_card_body"><div><strong>{item.name}</strong><span className={`visibility-${item.visibility}`}>{item.visibility === "public" ? "Público" : "Privado"}</span></div><p>{directoryBenefitLabel(item)} · {String(item.valid_from).slice(0, 10)} al {String(item.valid_until).slice(0, 10)}</p><small>{item.description || "Sin descripción"}</small></div><nav><button type="button" onClick={() => edit(item)} title="Editar"><FaPen /></button><button type="button" onClick={() => remove(item)} title="Eliminar"><FaTrash /></button></nav></article>)}</div>
    {editing && <form className="tags_directory_benefits_form" onSubmit={save}><div className="tags_directory_benefits_form_heading"><div><h3>{form.id ? "Editar beneficio" : "Nuevo beneficio"}</h3><p>La vigencia determina cuándo se mostrará públicamente.</p></div><button type="button" onClick={reset}>Cancelar</button></div><div className="tags_directory_benefits_form_grid">
      <label>Nombre del beneficio<input required value={form.name} onChange={event => update("name", event.target.value)} placeholder="Ej. 10% de descuento" /></label>
      <label>Tipo<select value={form.benefitType} onChange={event => update("benefitType", event.target.value)}><option value="amount">Monto fijo</option><option value="percentage">Porcentaje</option><option value="quantity">Promoción por cantidad</option></select></label>
      {form.benefitType !== "quantity" ? <label>{form.benefitType === "percentage" ? "Porcentaje" : "Monto"}<input required type="number" min="0" step="0.01" max={form.benefitType === "percentage" ? "100" : undefined} value={form.benefitValue} onChange={event => update("benefitValue", event.target.value)} /></label> : <><label>Comprá<input required type="number" min="2" step="1" value={form.promotionBuyQuantity} onChange={event => update("promotionBuyQuantity", event.target.value)} placeholder="2" /></label><label>Pagá<input required type="number" min="1" step="1" value={form.promotionPayQuantity} onChange={event => update("promotionPayQuantity", event.target.value)} placeholder="1" /></label><label>Producto o servicio<input value={form.promotionItem} onChange={event => update("promotionItem", event.target.value)} placeholder="Ej. empanadas" /></label></>}
      <label>Visibilidad<select value={form.visibility} onChange={event => update("visibility", event.target.value)}><option value="private">Privado · solo mi Web</option><option value="public">Público · Directorio</option></select></label><label>Válido desde<input required type="date" value={form.validFrom} onChange={event => update("validFrom", event.target.value)} /></label><label>Válido hasta<input required type="date" value={form.validUntil} onChange={event => update("validUntil", event.target.value)} /></label><label className="wide">Descripción<textarea value={form.description} onChange={event => update("description", event.target.value)} placeholder="Condiciones o detalle del beneficio" /></label><div className="wide tags_directory_benefits_upload"><span>Imagen del beneficio</span><MediaUploader businessId={businessId} module="directory" variant="benefit" entityId={form.id || pageId} value={form.imageUrl} onChange={media => update("imageUrl", media?.url || "")} /></div><label className="check"><input type="checkbox" checked={form.isActive} onChange={event => update("isActive", event.target.checked)} /> Beneficio activo</label></div><footer><button type="submit">Guardar beneficio</button></footer></form>}
  </div>;
}
