"use client";
import {useState} from "react";
import {Scanner} from "@yudiel/react-qr-scanner";
import {FaCamera,FaCheck,FaKeyboard,FaStore,FaXmark} from "react-icons/fa6";
import showAlert from "@/app/components/showAlert";
import "./LoyaltyMerchantClaim.css";

export default function LoyaltyMerchantClaim({onCreated}){
 const[code,setCode]=useState(""),[merchant,setMerchant]=useState(null),[rewards,setRewards]=useState([]),[scanner,setScanner]=useState(false),[mode,setMode]=useState("accrual"),[rewardId,setRewardId]=useState(""),[amount,setAmount]=useState(""),[notes,setNotes]=useState(""),[busy,setBusy]=useState(false);
 async function inspect(value=code){setBusy(true);try{const r=await fetch("/api/loyalty/member/merchant/lookup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({value})}),p=await r.json();if(!r.ok)throw new Error(p.error);setMerchant(p.merchant);setRewards(p.rewards||[]);setCode(String(value).replace(/^tags-loyalty-business:/i,""));}catch(e){await showAlert({title:"No se pudo identificar el comercio",text:e.message,icon:"error"})}finally{setBusy(false)}}
 async function create(e){e.preventDefault();setBusy(true);try{const r=await fetch("/api/loyalty/member/claims",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({business_id:merchant.business_id,program_id:merchant.program_id,merchant_identifier:code,claim_type:mode,reward_id:mode==="redemption"?rewardId:null,amount,notes})}),p=await r.json();if(!r.ok)throw new Error(p.error);setMerchant(null);setCode("");setAmount("");setNotes("");setRewardId("");await onCreated?.();await showAlert({title:"Solicitud enviada",text:"El comercio debe confirmarla para actualizar tu cuenta.",icon:"success"})}catch(error){await showAlert({title:"No se pudo enviar",text:error.message,icon:"error"})}finally{setBusy(false)}}
 function scanned(codes){const value=codes?.[0]?.rawValue;if(!value)return;setScanner(false);inspect(value)}
 return <section className="tags_loyalty_claim_start"><header><div><FaStore/><span><small>EN EL COMERCIO</small><h2>Registrar compra o visita</h2><p>Escaneá el QR del comercio o ingresá su código temporal.</p></span></div></header>{!merchant?<div className="tags_loyalty_claim_lookup"><button type="button" onClick={()=>setScanner(true)}><FaCamera/> Escanear QR</button><form onSubmit={e=>{e.preventDefault();inspect()}}><label><FaKeyboard/><input inputMode="numeric" value={code} onChange={e=>setCode(e.target.value.trim())} placeholder="Código del comercio"/></label><button disabled={busy}>Continuar</button></form></div>:<form className="tags_loyalty_claim_form" onSubmit={create}><div className="tags_loyalty_claim_merchant"><FaCheck/><span><small>COMERCIO IDENTIFICADO</small><strong>{merchant.business_name}</strong><em>{merchant.program_name}</em></span><button type="button" onClick={()=>setMerchant(null)}>Cambiar</button></div><label>¿Qué querés solicitar?<select value={mode} onChange={e=>setMode(e.target.value)}><option value="accrual">Registrar compra o visita</option>{rewards.length>0&&<option value="redemption">Canjear una recompensa</option>}</select></label>{mode==="redemption"?<label>Recompensa<select required value={rewardId} onChange={e=>setRewardId(e.target.value)}><option value="">Seleccionar</option>{rewards.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>:<label>Importe de la compra (opcional)<input type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label>}<label>Detalle (opcional)<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Ej. Compra en mostrador"/></label><button disabled={busy}>{busy?"Enviando...":"Enviar solicitud al comercio"}</button></form>}{scanner&&<div className="tags_loyalty_claim_scanner"><section><header><h2>Escanear QR del comercio</h2><button onClick={()=>setScanner(false)}><FaXmark/></button></header><Scanner constraints={{facingMode:"environment"}} onScan={scanned} onError={()=>{}}/><p>Enfocá el QR que muestra el comercio.</p></section></div>}</section>
}
