"use client";
import {useEffect,useState} from "react";
import {FaArrowsRotate,FaCheck,FaClock,FaQrcode,FaXmark} from "react-icons/fa6";
import showAlert from "@/app/components/showAlert";
import "./LoyaltyMerchantClaimsAdmin.css";

export default function LoyaltyMerchantClaimsAdmin({businessId,isAdmin}){
 const[code,setCode]=useState(null),[claims,setClaims]=useState([]),[busy,setBusy]=useState(false),[values,setValues]=useState({});const query=isAdmin?`?business_id=${businessId}`:"";
 async function load(){try{const[cr,lr]=await Promise.all([fetch(`/api/loyalty/admin/merchant-code${query}`),fetch(`/api/loyalty/admin/claims${query}`)]),cp=await cr.json(),lp=await lr.json();if(cr.ok)setCode(cp.code);if(lr.ok)setClaims(lp.claims||[])}catch{}}
 useEffect(()=>{load()},[businessId]);
 async function rotate(){const ok=await showAlert({title:"¿Generar un código nuevo?",text:"El código y QR actuales dejarán de funcionar.",icon:"warning",showCancelButton:true,confirmButtonText:"Generar",cancelButtonText:"Cancelar"});if(!ok)return;setBusy(true);try{const r=await fetch("/api/loyalty/admin/merchant-code",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({business_id:businessId})}),p=await r.json();if(!r.ok)throw new Error(p.error);setCode(p.code)}catch(e){showAlert({title:"No se pudo generar",text:e.message,icon:"error"})}finally{setBusy(false)}}
 async function review(item,action){const approving=action==="approve",ok=await showAlert({title:approving?"¿Confirmar esta solicitud?":"¿Rechazar esta solicitud?",text:approving?"El movimiento se acreditará en la cuenta del usuario.":"La solicitud quedará rechazada sin modificar saldos.",icon:"warning",showCancelButton:true,confirmButtonText:approving?"Confirmar":"Rechazar",cancelButtonText:"Cancelar"});if(!ok)return;setBusy(true);try{const amount=values[item.id]||1,r=await fetch("/api/loyalty/admin/claims",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({business_id:businessId,id:item.id,action,points:item.mechanic==="points"?amount:0,stamps:item.mechanic==="stamps"?amount:0,visits:item.mechanic==="visits"?amount:0})}),p=await r.json();if(!r.ok)throw new Error(p.error);await load();await showAlert({title:approving?"Solicitud confirmada":"Solicitud rechazada",icon:"success",timer:1400})}catch(e){showAlert({title:"No se pudo procesar",text:e.message,icon:"error"})}finally{setBusy(false)}}
 const pending=claims.filter(i=>i.status==="pending");return <section className="tags_loyalty_merchant_admin"><div className="tags_loyalty_merchant_code"><header><div><small>CÓDIGO DEL COMERCIO</small><h2>El cliente también puede iniciar la operación</h2><p>Mostrá este QR o código. Vence automáticamente a las 24 horas.</p></div><button onClick={rotate} disabled={busy}><FaArrowsRotate/> Regenerar</button></header>{code&&<div><img src={`https://api.qrserver.com/v1/create-qr-code/?size=260x260&data=${encodeURIComponent(code.qrValue)}`} alt="QR temporal del comercio"/><span><strong>{code.accessCode}</strong><small>Válido hasta {new Date(code.expiresAt).toLocaleString("es-AR")}</small></span></div>}</div><div className="tags_loyalty_claims_admin"><header><div><small>SOLICITUDES PENDIENTES</small><h2>Confirmar movimientos</h2></div><em>{pending.length}</em></header>{pending.map(item=><article key={item.id}><div><strong>{item.display_name||`${item.first_name} ${item.last_name}`}</strong><span>{item.email}</span><small>{item.claim_type==="redemption"?`Canje: ${item.reward_name}`:`${item.mechanic==="points"?"Compra / puntos":item.mechanic==="stamps"?"Agregar sellos":"Registrar visita"}${item.requested_amount?` · $ ${Number(item.requested_amount).toLocaleString("es-AR")}`:""}`}</small></div>{item.claim_type!=="redemption"&&<label>Cantidad<input type="number" min="1" value={values[item.id]||1} onChange={e=>setValues({...values,[item.id]:e.target.value})}/></label>}<nav><button title="Rechazar" onClick={()=>review(item,"reject")}><FaXmark/></button><button title="Confirmar" onClick={()=>review(item,"approve")}><FaCheck/> Confirmar</button></nav></article>)}{!pending.length&&<div className="tags_loyalty_claims_none"><FaClock/><p>No hay solicitudes pendientes.</p></div>}</div></section>
}
