"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import FullCalendar from "@fullcalendar/react";
import dayGridPlugin from "@fullcalendar/daygrid";
import timeGridPlugin from "@fullcalendar/timegrid";
import interactionPlugin from "@fullcalendar/interaction";
import esLocale from "@fullcalendar/core/locales/es";
import "./TurnosAdminCalendar.css";

const COLORS={pending:"#e7b72d",confirmed:"#22a35a",checked_in:"#367bd6",in_progress:"#7b52c7",completed:"#2b9a62",cancelled:"#b94040",rejected:"#8c4b4b",no_show:"#68717d"};
const LABELS={pending:"Pendiente",confirmed:"Confirmado",checked_in:"Presente",in_progress:"En curso",completed:"Finalizado",cancelled:"Cancelado",rejected:"Rechazado",no_show:"Ausente"};

export default function TurnosAdminCalendar({businessId,turnosId,onCreateRange}){
 const calendarRef=useRef(null),[bookings,setBookings]=useState([]),[selected,setSelected]=useState(null),[view,setView]=useState("timeGridWeek"),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);const q=new URLSearchParams({businessId:String(businessId),turnosId:String(turnosId)}),r=await fetch(`/api/turnos/admin/bookings?${q}`,{cache:"no-store"}),d=await r.json();if(r.ok)setBookings(d.bookings||[]);setLoading(false);}
 useEffect(()=>{if(!turnosId)return;load();const timer=setInterval(load,30000);const refresh=()=>{if(document.visibilityState==="visible")load();};document.addEventListener("visibilitychange",refresh);window.addEventListener("focus",refresh);return()=>{clearInterval(timer);document.removeEventListener("visibilitychange",refresh);window.removeEventListener("focus",refresh);};},[businessId,turnosId]);
 useEffect(()=>{const mobile=window.matchMedia("(max-width: 700px)").matches;setView(mobile?"timeGridDay":"timeGridWeek");},[]);
 const events=useMemo(()=>bookings.map(b=>({id:String(b.id),title:`${b.customer_name} · ${b.service_name}`,start:b.starts_at,end:b.ends_at,backgroundColor:COLORS[b.status]||"#5f6b76",borderColor:COLORS[b.status]||"#5f6b76",extendedProps:b})),[bookings]);
 function changeView(next){setView(next);calendarRef.current?.getApi().changeView(next);}
 return <section className="tags_turnos_admin_calendar"><header><div><span>AGENDA</span><h2>Calendario de reservas</h2></div><div className="tags_turnos_admin_calendar_views"><button className={view==="timeGridDay"?"is_active":""} onClick={()=>changeView("timeGridDay")}>Día</button><button className={view==="timeGridWeek"?"is_active":""} onClick={()=>changeView("timeGridWeek")}>Semana</button><button className={view==="dayGridMonth"?"is_active":""} onClick={()=>changeView("dayGridMonth")}>Mes</button></div></header>{loading&&<p className="tags_turnos_admin_calendar_loading">Actualizando agenda…</p>}<div className="tags_turnos_admin_calendar_frame"><FullCalendar ref={calendarRef} plugins={[dayGridPlugin,timeGridPlugin,interactionPlugin]} locale={esLocale} initialView={view} headerToolbar={{left:"prev,next today",center:"title",right:""}} buttonText={{today:"Hoy"}} events={events} selectable selectMirror nowIndicator allDaySlot={false} slotMinTime="06:00:00" slotMaxTime="24:00:00" height="auto" select={info=>onCreateRange?.({startsAt:info.startStr,endsAt:info.endStr})} eventClick={info=>setSelected(info.event.extendedProps)} eventContent={info=><div className="tags_turnos_admin_calendar_event"><strong>{info.timeText}</strong><span>{info.event.extendedProps.customer_name}</span><small>{info.event.extendedProps.resource_names||info.event.extendedProps.service_name}{Number(info.event.extendedProps.reserved_units)>0?` · ${info.event.extendedProps.reserved_units} unidad(es)`:""}</small></div>}/></div>{selected&&<div className="tags_turnos_admin_calendar_modal_backdrop" onMouseDown={()=>setSelected(null)}><section className="tags_turnos_admin_calendar_modal" onMouseDown={e=>e.stopPropagation()}><button className="tags_turnos_admin_calendar_modal_close" onClick={()=>setSelected(null)}>×</button><span className={`tags_turnos_admin_calendar_badge tags_turnos_admin_calendar_badge_${selected.status}`}>{LABELS[selected.status]||selected.status}</span><h3>{selected.customer_name}</h3><p>{selected.service_name}</p><dl><div><dt>Horario</dt><dd>{new Date(selected.starts_at).toLocaleString("es-AR")} – {new Date(selected.ends_at).toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"})}</dd></div><div><dt>Reserva</dt><dd>{selected.booking_number}</dd></div><div><dt>Recurso</dt><dd>{selected.resource_names||"Asignación automática"}</dd></div><div><dt>Cantidad</dt><dd>{selected.reserved_units||selected.party_size}</dd></div><div><dt>Contacto</dt><dd>{selected.customer_email||selected.customer_phone}</dd></div></dl></section></div>}</section>;
}
