"use client";

import { useEffect, useRef, useState } from "react";
import { FaBellConcierge, FaComments, FaPaperPlane, FaPlus, FaXmark } from "react-icons/fa6";
import TagsSpinner from "@/app/components/TagsSpinner";
import showAlert from "@/app/components/showAlert";
import "./GuestExperienceMessages.css";

const EMPTY={categoryId:"",details:"",requestedFor:""};
const statusText={open:"Pendiente",in_progress:"En atención",resolved:"Resuelta",cancelled:"Cancelada"};
async function read(response){const text=await response.text();if(!text)return{ok:false,error:`Respuesta vacía (${response.status})`};try{return JSON.parse(text)}catch{return{ok:false,error:"La respuesta del servidor no es válida"}}}
const when=value=>value?new Date(value).toLocaleString("es-AR",{dateStyle:"short",timeStyle:"short"}):"";

export default function GuestExperienceMessages({slug,previewData=null}){
 const[tab,setTab]=useState("messages"),[messages,setMessages]=useState(previewData?.messages||[]),[requests,setRequests]=useState(previewData?.requests||[]),[categories,setCategories]=useState(previewData?.categories||[]),[message,setMessage]=useState(""),[modal,setModal]=useState(false),[form,setForm]=useState(EMPTY),[busy,setBusy]=useState(!previewData),threadRef=useRef(null);
 async function load(silent=false){if(previewData)return;if(!silent)setBusy(true);try{const [messageResponse,requestResponse]=await Promise.all([fetch(`/api/guest-experience/public/messages?slug=${encodeURIComponent(slug)}`,{cache:"no-store"}),fetch(`/api/guest-experience/public/requests?slug=${encodeURIComponent(slug)}`,{cache:"no-store"})]),messagePayload=await read(messageResponse),requestPayload=await read(requestResponse);if(messageResponse.ok&&messagePayload.ok)setMessages(messagePayload.messages||[]);else if(!silent)await showAlert({title:"No se pudieron cargar los mensajes",text:messagePayload.error,icon:"error"});if(requestResponse.ok&&requestPayload.ok){setRequests(requestPayload.requests||[]);setCategories(requestPayload.categories||[])}else if(!silent)await showAlert({title:"No se pudieron cargar las solicitudes",text:requestPayload.error,icon:"error"})}finally{if(!silent)setBusy(false)}}
 useEffect(()=>{load();if(previewData)return;const timer=setInterval(()=>load(true),10000);return()=>clearInterval(timer)},[slug,previewData]);
 useEffect(()=>{if(threadRef.current)threadRef.current.scrollTop=threadRef.current.scrollHeight},[messages.length]);
 async function send(event){event.preventDefault();if(!message.trim()||previewData)return;setBusy(true);try{const response=await fetch("/api/guest-experience/public/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({slug,message})}),payload=await read(response);if(!response.ok||!payload.ok)return showAlert({title:"No se pudo enviar",text:payload.error,icon:"error"});setMessage("");await load(true)}finally{setBusy(false)}}
 async function createRequest(event){event.preventDefault();if(previewData)return;const category=categories.find(item=>String(item.id)===String(form.categoryId));if(!category)return showAlert({title:"Elegí un tipo de solicitud",icon:"warning"});if(Number(category.requires_schedule)&&!form.requestedFor)return showAlert({title:"Indicá fecha y hora",text:"Este tipo de solicitud necesita programación.",icon:"warning"});setBusy(true);try{const response=await fetch("/api/guest-experience/public/requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({slug,...form})}),payload=await read(response);if(!response.ok||!payload.ok)return showAlert({title:"No se pudo enviar",text:payload.error,icon:"error"});setModal(false);setForm(EMPTY);await load(true);await showAlert({title:"Solicitud enviada",text:"El alojamiento ya puede verla y mantenerte informado.",icon:"success",timer:1500})}finally{setBusy(false)}}
 async function cancel(item){const ok=await showAlert({title:"¿Cancelar esta solicitud?",text:item.title,icon:"warning",showCancelButton:true,confirmButtonText:"Cancelar solicitud",cancelButtonText:"Volver"});if(!ok)return;setBusy(true);try{const response=await fetch("/api/guest-experience/public/requests",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({slug,id:item.id})}),payload=await read(response);if(!response.ok||!payload.ok)return showAlert({title:"No se pudo cancelar",text:payload.error,icon:"error"});await load(true)}finally{setBusy(false)}}
 const selectedCategory=categories.find(item=>String(item.id)===String(form.categoryId));
 return <div className="tags_guest_contact_public"><header><span>CONTACTO DIRECTO</span><h2>Mensajes y solicitudes</h2><p>Escribinos o pedí un servicio durante tu estadía.</p></header><nav><button className={tab==="messages"?"is_active":""} onClick={()=>setTab("messages")}><FaComments/> Mensajes</button><button className={tab==="requests"?"is_active":""} onClick={()=>setTab("requests")}><FaBellConcierge/> Solicitudes</button></nav>
 {tab==="messages"&&<section className="tags_guest_contact_chat"><div ref={threadRef}>{messages.map(item=><article key={item.id} className={`is_${item.sender_type}`}><span>{item.sender_type==="guest"?"Vos":item.sender_type==="system"?"Actualización":item.sender_name||"Alojamiento"}</span><p>{item.message}</p><small>{when(item.created_at)}</small></article>)}{!messages.length&&<div className="tags_guest_contact_empty"><FaComments/><strong>¿En qué podemos ayudarte?</strong><span>Tu mensaje será recibido por el alojamiento.</span></div>}</div><form onSubmit={send}><textarea required value={message} onChange={event=>setMessage(event.target.value)} placeholder="Escribí tu mensaje…"/><button disabled={busy||!message.trim()||Boolean(previewData)}><FaPaperPlane/><span>Enviar</span></button></form></section>}
 {tab==="requests"&&<section className="tags_guest_contact_requests"><button className="tags_guest_contact_new" onClick={()=>setModal(true)} disabled={Boolean(previewData)}><FaPlus/> Nueva solicitud</button><div>{requests.map(item=><article key={item.id}><header><h3>{item.category_name}</h3><span className={`is_${item.status}`}>{statusText[item.status]||item.status}</span></header>{item.details&&<p>{item.details}</p>}{item.requested_for&&<dl><dt>Fecha y hora preferida</dt><dd>{when(item.requested_for)}</dd></dl>}{item.resolution_notes&&<blockquote>{item.resolution_notes}</blockquote>}<footer><small>Enviada {when(item.created_at)}</small>{item.status==="open"&&<button onClick={()=>cancel(item)}>Cancelar</button>}</footer></article>)}{!requests.length&&<div className="tags_guest_contact_empty"><FaBellConcierge/><strong>No tenés solicitudes</strong><span>Podés pedir limpieza, mantenimiento u otros servicios disponibles.</span></div>}</div></section>}
 {modal&&<div className="tags_guest_contact_backdrop" onMouseDown={()=>!busy&&setModal(false)}><section className="tags_guest_contact_modal" onMouseDown={event=>event.stopPropagation()}><header><div><span>NUEVA SOLICITUD</span><h3>¿Qué necesitás?</h3></div><button onClick={()=>setModal(false)} aria-label="Cerrar"><FaXmark/></button></header><form onSubmit={createRequest}><label>Tipo de solicitud *<select required value={form.categoryId} onChange={event=>setForm({...form,categoryId:event.target.value})}><option value="">Seleccionar</option>{categories.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{Number(selectedCategory?.requires_schedule)===1&&<label>Fecha y hora preferida *<input required type="datetime-local" value={form.requestedFor} onChange={event=>setForm({...form,requestedFor:event.target.value})}/></label>}<label>Detalle<textarea maxLength="3000" value={form.details} onChange={event=>setForm({...form,details:event.target.value})} placeholder="Agregá todo lo que necesitemos saber"/></label><button disabled={busy}>Enviar solicitud</button></form></section></div>}{busy&&<TagsSpinner size={100} logoSize={52} borderSize={5} background="rgba(255,255,255,.72)"/>}</div>;
}
