"use client";
import { useEffect, useMemo, useState } from "react";
import QRCode from "qrcode";
import { FaCheck, FaClock, FaGift, FaLocationDot, FaQrcode, FaStore, FaXmark } from "react-icons/fa6";
import TagsSpinner from "@/app/components/TagsSpinner";
import showAlert from "@/app/components/showAlert";
import "./GuestExperienceBenefits.css";

async function read(response){const text=await response.text();if(!text)return{ok:false,error:`Respuesta vacía (${response.status})`};try{return JSON.parse(text)}catch{return{ok:false,error:"La respuesta del servidor no es válida"}}}
function CouponQr({value}){const[src,setSrc]=useState("");useEffect(()=>{QRCode.toDataURL(value,{width:280,margin:2,color:{dark:"#173d2b",light:"#ffffff"}}).then(setSrc).catch(()=>setSrc(""))},[value]);return src?<img className="tags_guest_coupon_qr" src={src} alt="Código QR del cupón"/>:<TagsSpinner size={70} logoSize={36}/>}
const statusLabel=status=>status==="redeemed"?"Canjeado":status==="expired"?"Vencido":status==="cancelled"?"Cancelado":"Disponible";

export default function GuestExperienceBenefits({slug,previewData=null}){
 const[data,setData]=useState(previewData),[busy,setBusy]=useState(!previewData),[category,setCategory]=useState("all"),[selected,setSelected]=useState(null);
 async function load(silent=false){if(!silent)setBusy(true);try{const response=await fetch(`/api/guest-experience/public/benefits?slug=${encodeURIComponent(slug)}`,{cache:"no-store"}),payload=await read(response);if(response.ok&&payload.ok){setData(payload);setSelected(current=>current?payload.campaigns.flatMap(item=>item.coupons.map(coupon=>({...coupon,campaign:item}))).find(item=>item.id===current.id)||current:null)}else if(!silent)await showAlert({title:"No se pudieron cargar",text:payload.error,icon:"error"})}finally{if(!silent)setBusy(false)}}
 useEffect(()=>{if(previewData)return;load();const timer=setInterval(()=>load(true),20000);return()=>clearInterval(timer)},[slug,previewData]);
 async function issue(campaign){const ok=await showAlert({title:"¿Generar este cupón?",text:`${campaign.name} · ${campaign.merchant_name}. Una vez generado contará dentro de tu límite disponible.`,icon:"question",showCancelButton:true,confirmButtonText:"Generar cupón",cancelButtonText:"Cancelar"});if(!ok)return;setBusy(true);try{const response=await fetch("/api/guest-experience/public/benefits",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({slug,campaignId:campaign.id})}),payload=await read(response);if(!response.ok||!payload.ok)return showAlert({title:"No se pudo generar",text:payload.error,icon:"error"});await load(true);setSelected({...payload.coupon,campaign});await showAlert({title:"Cupón generado",text:"Mostrá el QR en el comercio para utilizarlo.",icon:"success",timer:1500})}finally{setBusy(false)}}
 const campaigns=useMemo(()=>(data?.campaigns||[]).filter(item=>category==="all"||String(item.category_id)===category),[data,category]);
 if(busy&&!data)return <div className="tags_guest_benefits_loading"><TagsSpinner size={88} logoSize={46}/></div>;
 return <div className="tags_guest_benefits_public"><header><span>BENEFICIOS PARA TU ESTADÍA</span><h2>Beneficios y cupones</h2><p>Generá el cupón y presentalo desde tu teléfono en el comercio.</p></header><nav><button className={category==="all"?"is_active":""} onClick={()=>setCategory("all")}>Todos</button>{(data?.categories||[]).map(item=><button key={item.id} className={category===String(item.id)?"is_active":""} onClick={()=>setCategory(String(item.id))}>{item.name}</button>)}</nav><section>{campaigns.map(campaign=>{const available=campaign.coupons.filter(item=>item.status==="issued"),used=campaign.coupons.filter(item=>item.status==="redeemed");return <article key={campaign.id}>{campaign.image_url?<img src={campaign.image_url} alt={campaign.name}/>:<div className="tags_guest_benefits_placeholder"><FaGift/></div>}<div><small>{campaign.category_name||"Beneficio"}</small><h3>{campaign.name}</h3><strong><FaStore/> {campaign.merchant_name}</strong>{campaign.location_name&&<span><FaLocationDot/> {campaign.location_name}</span>}<p>{campaign.description}</p>{campaign.conditions_text&&<details><summary>Ver condiciones</summary><p>{campaign.conditions_text}</p></details>}<footer>{available.map(coupon=><button className="is_coupon" key={coupon.id} onClick={()=>setSelected({...coupon,campaign})}><FaQrcode/> Ver cupón</button>)}{available.length+used.length<Number(campaign.max_issues||1)&&<button className="is_issue" onClick={()=>issue(campaign)}><FaGift/> Generar cupón</button>}{used.length>0&&<span className="is_used"><FaCheck/> {used.length} canjeado{used.length===1?"":"s"}</span>}</footer></div></article>})}{!campaigns.length&&<p>No hay beneficios publicados en esta categoría.</p>}</section>{selected&&<div className="tags_guest_coupon_backdrop" onMouseDown={()=>setSelected(null)}><section className="tags_guest_coupon_modal" onMouseDown={event=>event.stopPropagation()}><button className="tags_guest_coupon_close" onClick={()=>setSelected(null)} aria-label="Cerrar"><FaXmark/></button><span>CUPÓN TAGS</span><h2>{selected.campaign.name}</h2><strong>{selected.campaign.merchant_name}</strong><div className={`tags_guest_coupon_status is_${selected.status}`}>{selected.status==="redeemed"?<FaCheck/>:<FaClock/>}{statusLabel(selected.status)}</div><CouponQr value={selected.qrPayload}/><code>{selected.code}</code>{selected.campaign.usage_instructions&&<p>{selected.campaign.usage_instructions}</p>}<small>Válido hasta {new Date(selected.expiresAt).toLocaleString("es-AR")}</small>{selected.status==="redeemed"&&<p className="tags_guest_coupon_redeemed">Canjeado el {new Date(selected.redeemedAt).toLocaleString("es-AR")}</p>}</section></div>}{busy&&<TagsSpinner size={110} logoSize={58} borderSize={5} background="rgba(255,255,255,.72)"/>}</div>
}
