"use client";

import { useEffect, useState } from "react";
import { FaCar, FaCircleCheck, FaPlus, FaTrash, FaUser } from "react-icons/fa6";
import TagsSpinner from "@/app/components/TagsSpinner";
import showAlert from "@/app/components/showAlert";
import "./GuestExperiencePrecheckin.css";

const EMPTY_PERSON={id:0,firstName:"",lastName:"",documentType:"DNI",documentNumber:"",nationality:"",dateOfBirth:"",address:""};
const emailValid=value=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(value||"").trim());
const phoneValid=value=>String(value||"").replace(/\D/g,"").length>=8;

function Field({label,required=false,error="",wide=false,errorKey,children}) {
    return <label data-error-key={errorKey} className={`${wide?"wide ":""}${error?"is_invalid":""}`}><span>{label}{required&&<b aria-hidden="true"> *</b>}</span>{children}{error&&<small className="tags_guest_precheckin_error">{error}</small>}</label>;
}

export default function GuestExperiencePrecheckin({slug,onStatusChange,onSubmitted,previewData=null}) {
    const previewName=String(previewData?.guest?.name||"").split(" "),previewState=previewData?{status:previewData.stay?.precheckinStatus||"draft",readOnly:true,expectedCompanions:Math.max(0,Number(previewData.stay?.adults||0)+Number(previewData.stay?.children||0)-1),primary:{...EMPTY_PERSON,firstName:previewName.shift()||"",lastName:previewName.join(" "),documentNumber:previewData.guest?.documentNumber||"",email:previewData.guest?.email||"",phone:previewData.guest?.phone||"",privacyConsent:false},companions:[],vehicle:{plate:"",makeModel:"",color:""},expectedArrivalText:"",guestNotes:""}:null;
    const [data,setData]=useState(previewState),[busy,setBusy]=useState(!previewState),[errors,setErrors]=useState({});
    async function load(){setBusy(true);try{const response=await fetch(`/api/guest-experience/public/precheckin?slug=${encodeURIComponent(slug)}`,{cache:"no-store"}),payload=await response.json();if(!response.ok)return showAlert({title:"No se pudo abrir",text:payload.error,icon:"error"});setData(payload)}finally{setBusy(false)}}
    useEffect(()=>{if(!previewData)load()},[slug,previewData]);
    function clearError(key){setErrors(current=>{if(!current[key])return current;const next={...current};delete next[key];return next})}
    function setPrimary(key,value){clearError(`primary.${key}`);setData(current=>({...current,primary:{...current.primary,[key]:value}}))}
    function setVehicle(key,value){setData(current=>({...current,vehicle:{...current.vehicle,[key]:value}}))}
    function setCompanion(index,key,value){clearError(`companions.${index}.${key}`);setData(current=>({...current,companions:current.companions.map((person,position)=>position===index?{...person,[key]:value}:person)}))}
    function addCompanion(){if(data.companions.length>=data.expectedCompanions)return;clearError("companions");setData({...data,companions:[...data.companions,{...EMPTY_PERSON}]})}
    function validate(){const next={};const required=(key,value,message)=>{if(!String(value||"").trim())next[key]=message};required("primary.firstName",data.primary.firstName,"Ingresá el nombre del titular.");required("primary.lastName",data.primary.lastName,"Ingresá el apellido del titular.");required("primary.documentNumber",data.primary.documentNumber,"Ingresá el documento del titular.");required("primary.nationality",data.primary.nationality,"Indicá la nacionalidad del titular.");required("primary.dateOfBirth",data.primary.dateOfBirth,"Indicá la fecha de nacimiento.");required("primary.address",data.primary.address,"Ingresá el domicilio del titular.");required("primary.phone",data.primary.phone,"Ingresá un teléfono de contacto.");required("primary.email",data.primary.email,"Ingresá un email de contacto.");if(data.primary.email&&!emailValid(data.primary.email))next["primary.email"]="El formato del email no es válido.";if(data.primary.phone&&!phoneValid(data.primary.phone))next["primary.phone"]="El teléfono debe contener al menos 8 números.";if(data.companions.length!==data.expectedCompanions)next.companions=`Debés cargar ${data.expectedCompanions} acompañante${data.expectedCompanions===1?"":"s"}.`;data.companions.forEach((person,index)=>{required(`companions.${index}.firstName`,person.firstName,"Ingresá el nombre.");required(`companions.${index}.lastName`,person.lastName,"Ingresá el apellido.");required(`companions.${index}.documentNumber`,person.documentNumber,"Ingresá el documento.");required(`companions.${index}.nationality`,person.nationality,"Indicá la nacionalidad.");required(`companions.${index}.dateOfBirth`,person.dateOfBirth,"Indicá la fecha de nacimiento.")});if(!data.primary.privacyConsent)next["primary.privacyConsent"]="Tenés que aceptar las políticas y el tratamiento de datos.";return next}
    function focusFirstError(problems){const first=Object.keys(problems)[0];setTimeout(()=>{const target=document.querySelector(`[data-error-key="${first}"]`);target?.scrollIntoView({behavior:"smooth",block:"center"});target?.querySelector("input,select,textarea,button")?.focus()},50)}
    async function save(submit){if(submit){const problems=validate();setErrors(problems);if(Object.keys(problems).length){focusFirstError(problems);await showAlert({title:"Faltan datos para enviar",text:`${Object.values(problems)[0]} Revisá los campos marcados en rojo.`,icon:"warning"});return}const confirmed=await showAlert({title:"¿Enviar el pre-check-in?",text:"El establecimiento recibirá los datos para revisarlos antes de tu llegada.",icon:"question",showCancelButton:true,confirmButtonText:"Enviar pre-check-in",cancelButtonText:"Seguir revisando"});if(!confirmed)return}else setErrors({});setBusy(true);try{const response=await fetch(`/api/guest-experience/public/precheckin?slug=${encodeURIComponent(slug)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...data,submit})}),payload=await response.json();if(!response.ok)return showAlert({title:"No se pudo guardar",text:payload.error,icon:"error"});setData(current=>({...current,status:payload.status}));onStatusChange?.(payload.status);await showAlert({title:submit?"Pre-check-in enviado":"Borrador guardado",text:submit?"Tus datos quedaron disponibles para que el alojamiento los revise.":"Podés volver y completarlo en otro momento.",icon:"success",timer:1900});if(submit)onSubmitted?.()}finally{setBusy(false)}}
    if(!data)return <div className="tags_guest_precheckin_loading">{busy&&<TagsSpinner size={105} logoSize={55} borderSize={4} background="rgba(255,255,255,.8)"/>}</div>;
    const readOnly=data.readOnly,statusText=data.status==="checked_in"?"Check-in confirmado":data.status==="reviewed"?"Revisado por el alojamiento":data.status==="submitted"?"Enviado para revisión":"Pendiente de completar";
    return <section className="tags_guest_precheckin">
        <header><div><span>ANTES DE TU LLEGADA</span><h2>Pre-Check-in</h2><p>Los campos identificados con <b>*</b> son obligatorios para enviar el formulario.</p></div><strong className={`status_${data.status}`}><FaCircleCheck/>{statusText}</strong></header>
        <fieldset disabled={readOnly}><legend><FaUser/> Titular de la reserva</legend><div className="tags_guest_precheckin_fields">
            <Field label="Nombre" required error={errors["primary.firstName"]} errorKey="primary.firstName"><input aria-invalid={Boolean(errors["primary.firstName"])} value={data.primary.firstName} onChange={event=>setPrimary("firstName",event.target.value)}/></Field>
            <Field label="Apellido" required error={errors["primary.lastName"]} errorKey="primary.lastName"><input aria-invalid={Boolean(errors["primary.lastName"])} value={data.primary.lastName} onChange={event=>setPrimary("lastName",event.target.value)}/></Field>
            <Field label="Tipo de documento"><select value={data.primary.documentType} onChange={event=>setPrimary("documentType",event.target.value)}><option>DNI</option><option>Pasaporte</option><option>Otro</option></select></Field>
            <Field label="Número de documento" required error={errors["primary.documentNumber"]} errorKey="primary.documentNumber"><input aria-invalid={Boolean(errors["primary.documentNumber"])} value={data.primary.documentNumber} onChange={event=>setPrimary("documentNumber",event.target.value)}/></Field>
            <Field label="Nacionalidad" required error={errors["primary.nationality"]} errorKey="primary.nationality"><input aria-invalid={Boolean(errors["primary.nationality"])} value={data.primary.nationality} onChange={event=>setPrimary("nationality",event.target.value)}/></Field>
            <Field label="Fecha de nacimiento" required error={errors["primary.dateOfBirth"]} errorKey="primary.dateOfBirth"><input aria-invalid={Boolean(errors["primary.dateOfBirth"])} type="date" value={String(data.primary.dateOfBirth||"").slice(0,10)} onChange={event=>setPrimary("dateOfBirth",event.target.value)}/></Field>
            <Field label="Domicilio" required wide error={errors["primary.address"]} errorKey="primary.address"><input aria-invalid={Boolean(errors["primary.address"])} value={data.primary.address} onChange={event=>setPrimary("address",event.target.value)}/></Field>
            <Field label="Teléfono" required error={errors["primary.phone"]} errorKey="primary.phone"><input aria-invalid={Boolean(errors["primary.phone"])} type="tel" value={data.primary.phone} onChange={event=>setPrimary("phone",event.target.value)}/></Field>
            <Field label="Email" required error={errors["primary.email"]} errorKey="primary.email"><input aria-invalid={Boolean(errors["primary.email"])} type="email" value={data.primary.email} onChange={event=>setPrimary("email",event.target.value)}/></Field>
        </div></fieldset>
        <fieldset disabled={readOnly} className={errors.companions?"is_invalid_group":""} data-error-key="companions"><legend>Acompañantes <small>{data.companions.length} de {data.expectedCompanions}</small></legend>{errors.companions&&<p className="tags_guest_precheckin_group_error">{errors.companions}</p>}<div className="tags_guest_precheckin_people">
            {data.companions.map((person,index)=><article key={person.id||index}><header><strong>Pasajero {index+2}</strong><button type="button" aria-label="Eliminar acompañante" onClick={()=>{setErrors({});setData({...data,companions:data.companions.filter((_,position)=>position!==index)})}}><FaTrash/></button></header><div className="tags_guest_precheckin_fields"><Field label="Nombre" required error={errors[`companions.${index}.firstName`]} errorKey={`companions.${index}.firstName`}><input aria-invalid={Boolean(errors[`companions.${index}.firstName`])} value={person.firstName} onChange={event=>setCompanion(index,"firstName",event.target.value)}/></Field><Field label="Apellido" required error={errors[`companions.${index}.lastName`]} errorKey={`companions.${index}.lastName`}><input aria-invalid={Boolean(errors[`companions.${index}.lastName`])} value={person.lastName} onChange={event=>setCompanion(index,"lastName",event.target.value)}/></Field><Field label="Tipo de documento"><select value={person.documentType} onChange={event=>setCompanion(index,"documentType",event.target.value)}><option>DNI</option><option>Pasaporte</option><option>Otro</option></select></Field><Field label="Número de documento" required error={errors[`companions.${index}.documentNumber`]} errorKey={`companions.${index}.documentNumber`}><input aria-invalid={Boolean(errors[`companions.${index}.documentNumber`])} value={person.documentNumber} onChange={event=>setCompanion(index,"documentNumber",event.target.value)}/></Field><Field label="Nacionalidad" required error={errors[`companions.${index}.nationality`]} errorKey={`companions.${index}.nationality`}><input aria-invalid={Boolean(errors[`companions.${index}.nationality`])} value={person.nationality} onChange={event=>setCompanion(index,"nationality",event.target.value)}/></Field><Field label="Fecha de nacimiento" required error={errors[`companions.${index}.dateOfBirth`]} errorKey={`companions.${index}.dateOfBirth`}><input aria-invalid={Boolean(errors[`companions.${index}.dateOfBirth`])} type="date" value={String(person.dateOfBirth||"").slice(0,10)} onChange={event=>setCompanion(index,"dateOfBirth",event.target.value)}/></Field></div></article>)}
            {data.companions.length<data.expectedCompanions&&<button className="tags_guest_precheckin_add" type="button" onClick={addCompanion}><FaPlus/> Agregar acompañante</button>}
        </div></fieldset>
        <fieldset disabled={readOnly}><legend><FaCar/> Llegada y vehículo</legend><div className="tags_guest_precheckin_fields"><Field label="Patente"><input value={data.vehicle.plate} onChange={event=>setVehicle("plate",event.target.value.toUpperCase())}/></Field><Field label="Marca y modelo"><input value={data.vehicle.makeModel} onChange={event=>setVehicle("makeModel",event.target.value)}/></Field><Field label="Color"><input value={data.vehicle.color} onChange={event=>setVehicle("color",event.target.value)}/></Field><Field label="Horario estimado de llegada" wide><input placeholder="Ej. entre las 18 y las 19" value={data.expectedArrivalText} onChange={event=>setData({...data,expectedArrivalText:event.target.value})}/></Field><Field label="Observaciones" wide><textarea placeholder="Información que debamos conocer antes de tu llegada" value={data.guestNotes} onChange={event=>setData({...data,guestNotes:event.target.value})}/></Field></div></fieldset>
        {!readOnly&&<><label data-error-key="primary.privacyConsent" className={`tags_guest_precheckin_consent ${errors["primary.privacyConsent"]?"is_invalid":""}`}><input aria-invalid={Boolean(errors["primary.privacyConsent"])} type="checkbox" checked={data.primary.privacyConsent} onChange={event=>setPrimary("privacyConsent",event.target.checked)}/><span>Acepto las políticas del alojamiento y el tratamiento de los datos necesarios para gestionar mi estadía. <b>*</b>{errors["primary.privacyConsent"]&&<small className="tags_guest_precheckin_error">{errors["primary.privacyConsent"]}</small>}</span></label><div className="tags_guest_precheckin_actions"><button type="button" onClick={()=>save(false)}>Guardar borrador</button><button type="button" onClick={()=>save(true)}>Enviar pre-check-in</button></div></>}
        {busy&&<TagsSpinner size={105} logoSize={55} borderSize={4} background="rgba(255,255,255,.78)"/>}
    </section>;
}
