"use client";
import { useEffect, useState } from "react";
import { FaLocationArrow, FaMapLocationDot, FaPhone, FaWhatsapp, FaXmark } from "react-icons/fa6";
import TagsSpinner from "@/app/components/TagsSpinner";
import showAlert from "@/app/components/showAlert";
import "./GuestExperienceNearbyPlaces.css";
import "./GuestExperienceNearbyMapModal.css";

const distance = value => value == null ? "" : value < 1 ? `A ${Math.round(value * 1000)} m` : `A ${value.toLocaleString("es-AR", { maximumFractionDigits: 1 })} km`;
function whatsappNumber(value) { let digits = String(value || "").replace(/\D/g, ""); if (digits.startsWith("00")) digits = digits.slice(2); if (digits.startsWith("54")) return digits.startsWith("549") ? digits : `549${digits.slice(2).replace(/^15/, "")}`; digits = digits.replace(/^0/, "").replace(/^15/, ""); return digits ? `549${digits}` : ""; }
const routeUrl = place => `https://www.google.com/maps/dir/?api=1&destination=${place.latitude},${place.longitude}`;

export default function GuestExperienceNearbyPlaces({ slug, previewData = null }) {
    const [data, setData] = useState(previewData), [busy, setBusy] = useState(!previewData), [category, setCategory] = useState("all"), [mapPlace, setMapPlace] = useState(null);
    useEffect(() => { if (previewData) return; fetch(`/api/guest-experience/public/nearby?slug=${encodeURIComponent(slug)}`, { cache: "no-store" }).then(async response => ({ response, payload: await response.json() })).then(({ response, payload }) => response.ok ? setData(payload) : showAlert({ title: "No se pudo cargar", text: payload.error, icon: "error" })).finally(() => setBusy(false)); }, [slug, previewData]);
    useEffect(() => { if (!mapPlace) return; const close = event => event.key === "Escape" && setMapPlace(null); window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [mapPlace]);
    if (busy) return <div className="tags_guest_nearby_loading"><TagsSpinner size={88} logoSize={46} /></div>;
    const places = (data?.places || []).filter(place => category === "all" || String(place.category_id) === category);
    return <div className="tags_guest_nearby_public"><header><span>QUÉ HAY CERCA</span><h2>Lugares cercanos</h2><p>Comercios, servicios y atractivos recomendados durante tu estadía.</p></header><nav><button className={category === "all" ? "is_active" : ""} onClick={() => setCategory("all")}>Todos</button>{(data?.categories || []).map(item => <button className={category === String(item.id) ? "is_active" : ""} key={item.id} onClick={() => setCategory(String(item.id))}>{item.name}</button>)}</nav><section>{places.map(place => <article key={place.id}>{place.image_url ? <img src={place.image_url} alt={place.name} /> : <div className="tags_guest_nearby_placeholder"><FaMapLocationDot /></div>}<div className="tags_guest_nearby_body"><small>{distance(place.distanceKm)} de {data.originLabel}</small><h3>{place.name}</h3>{place.description && <p>{place.description}</p>}<address>{place.address}</address>{place.opening_hours && <small>{place.opening_hours}</small>}<div>{place.phone && <a href={`tel:${place.phone}`}><FaPhone /> Llamar</a>}{place.whatsapp && <a href={`https://wa.me/${whatsappNumber(place.whatsapp)}`} target="_blank" rel="noreferrer"><FaWhatsapp /> WhatsApp</a>}<button type="button" onClick={() => setMapPlace(place)}><FaMapLocationDot /> Ver mapa</button><a className="is_route" href={routeUrl(place)} target="_blank" rel="noreferrer"><FaLocationArrow /> Cómo llegar</a></div></div></article>)}{!places.length && <p>No hay lugares publicados en esta categoría.</p>}</section>{mapPlace && <div className="tags_guest_nearby_map_backdrop" onMouseDown={() => setMapPlace(null)}><section className="tags_guest_nearby_map_modal" onMouseDown={event => event.stopPropagation()}><header><div><small>UBICACIÓN</small><h3>{mapPlace.name}</h3><p>{mapPlace.address}</p></div><button type="button" onClick={() => setMapPlace(null)} aria-label="Cerrar mapa"><FaXmark /></button></header><iframe title={`Mapa de ${mapPlace.name}`} loading="lazy" src={`https://www.google.com/maps?q=${mapPlace.latitude},${mapPlace.longitude}&z=15&output=embed`} /><footer><a href={routeUrl(mapPlace)} target="_blank" rel="noreferrer"><FaLocationArrow /> Cómo llegar</a></footer></section></div>}</div>;
}
