"use client";
import { useEffect,useState } from "react";
import { FaClock,FaCopy,FaEnvelope,FaListCheck,FaPhone,FaWifi } from "react-icons/fa6";
import TagsSpinner from "@/app/components/TagsSpinner";
import showAlert from "@/app/components/showAlert";
import "./GuestExperienceInformation.css";
export default function GuestExperienceInformation({slug,previewData=null}){
 const[data,setData]=useState(previewData),[busy,setBusy]=useState(!previewData);
 useEffect(()=>{if(previewData)return;fetch(`/api/guest-experience/public/information?slug=${encodeURIComponent(slug)}`,{cache:"no-store"}).then(async response=>({response,payload:await response.json()})).then(({response,payload})=>response.ok?setData(payload):showAlert({title:"No se pudo cargar",text:payload.error,icon:"error"})).finally(()=>setBusy(false))},[slug,previewData]);
 async function copy(value){try{await navigator.clipboard.writeText(value);await showAlert({title:"Clave copiada",text:"Ya podés pegarla en la configuración WiFi.",icon:"success",timer:1400})}catch{await showAlert({title:"No se pudo copiar",text:"Mantené presionada la clave para copiarla.",icon:"warning"})}}
 if(busy)return <div className="tags_guest_information_loading"><TagsSpinner size={88} logoSize={46} borderSize={4}/></div>;
 const info=data?.information||{},networks=data?.wifiNetworks||[];
 return <div className="tags_guest_information"><header><span>INFORMACIÓN ÚTIL</span><h2>Todo para tu estadía</h2><p>Accesos, horarios e indicaciones del alojamiento.</p></header><section><h3><FaWifi/> Redes WiFi</h3>{networks.length?<div className="tags_guest_information_wifi">{networks.map(network=><article key={network.id}><small>{network.sector||"Alojamiento"}</small><strong>{network.networkName}</strong>{network.password&&<div><code>{network.password}</code><button type="button" onClick={()=>copy(network.password)}><FaCopy/> Copiar clave</button></div>}{network.instructions&&<p>{network.instructions}</p>}</article>)}</div>:<p className="tags_guest_information_empty">El alojamiento todavía no publicó redes WiFi.</p>}</section>{(info.checkinTime||info.checkoutTime||info.arrivalInstructions||info.departureInstructions)&&<section><h3><FaClock/> Ingreso y egreso</h3><div className="tags_guest_information_times">{info.checkinTime&&<div><small>Ingreso desde</small><strong>{info.checkinTime}</strong></div>}{info.checkoutTime&&<div><small>Egreso hasta</small><strong>{info.checkoutTime}</strong></div>}</div>{info.arrivalInstructions&&<article><strong>Para llegar</strong><p>{info.arrivalInstructions}</p></article>}{info.departureInstructions&&<article><strong>Antes de retirarte</strong><p>{info.departureInstructions}</p></article>}</section>}{info.houseRules&&<section><h3><FaListCheck/> Recomendaciones y normas</h3><p>{info.houseRules}</p></section>}{(info.receptionPhone||info.receptionEmail)&&<section><h3>Contacto del alojamiento</h3><div className="tags_guest_information_contacts">{info.receptionPhone&&<a href={`tel:${info.receptionPhone}`}><FaPhone/>{info.receptionPhone}</a>}{info.receptionEmail&&<a href={`mailto:${info.receptionEmail}`}><FaEnvelope/>{info.receptionEmail}</a>}</div></section>}</div>
}
